### ISSUE TITLE
512MB memory is not enough to ros install (0.4.1)

### ISSUE THREAD

**Issue by robbertkl** [rancher/os#658] opened 2015-11-24 17:06 UTC
http://docs.rancher.com/os/running-rancheros/workstation/boot-from-iso/ states:

> You must boot with at least 512MB of memory.

However, to perform a `ros install` for 0.4.1, this is not enough. I would suggest changing the documentation to 1024MB, I've confirmed this is enough to perform an installation.

**Comment by deniseschannon** [comment] 2015-11-24 17:30
This is a duplicate of https://github.com/rancher/os/issues/608, but probably better worded. Will close the other in favor of this one.

**Comment by deniseschannon** [comment] 2015-11-24 17:40
I've updated the documentation with a note that if you are planning to install to disk, you'll need 1024 MB.

**Comment by robbertkl** [comment] 2015-11-25 01:05
Thanks for the updating the documentation. Guess this issue can be closed now?

**Comment by deniseschannon** [comment] 2015-11-25 04:06
No, we'd like to allow the ability to install using 512MB. So we'll keep it open.

**Comment by liyimeng** [comment] 2016-02-27 14:26
If using alpine linux instead of debian image for system installer, it should be possible to decrease memory need, right?

**Comment by ibuildthecloud** [comment] 2016-02-27 15:40
@liyimeng the problem with alpine is that there isn't support for grub2.  I'm not inclined to switch to syslinux.  Basically we just need to build a custom installer image that has grub but not based on Debian.  Should be doable but we just haven't had the time to do it.

**Comment by liyimeng** [comment] 2016-02-29 14:18
@ibuildthecloud syslinux is simple,  also feature rich, not a bad idea to go with it.

**Comment by ibuildthecloud** [comment] 2016-02-29 16:44
@liyimeng I like the simplicity.  I'm just not sure about the feature rich part.  If it truly is then maybe we should.  Honestly I don't have enough experience with it from a "production" sense.  My context of using syslinux is typically LiveCDs and also XenServer I believe was built on extlinux.  If you think there is a strong case for syslinux it would greatly simplify things.  @imikushin has already done some work in this area and moving to alpine + syslinux for our installer will make it so that we could run with less memory.

**Comment by ibuildthecloud** [comment] 2016-02-29 16:45
@liyimeng perusing over https://wiki.archlinux.org/index.php/syslinux seems to indicate syslinux has a lot more feature than I knew of.

**Comment by SvenDowideit** [comment] 2018-01-30 01:21
asdf

**Closed** 2018-12-18 01:45 UTC
Labels: area/packaging, kind/enhancement, priority/p1

**Comment by niusmallnan** [comment] 2018-12-18 09:02
The full RancherOS is no longer able to support 512MB.
For the next release v1.5.0, at least 1GB is required.

If the user adjusts user-docker and kernel and system-images, you can use 512MB memory, but this requires a custom build. It's difficult for most users.

**Comment by wiktor-k** [comment] 2018-12-18 09:04
Got it, thanks for taking the time to explain!
