### ISSUE TITLE
Extend Disk Size in RancherOS for AWS instances

### ISSUE THREAD

**Issue by bscott** [rancher/os#232] opened 2015-04-24 20:41 UTC
Hello,

I started my RancherOS AMI's with 500GB Disk's but RancherOS only see's 7GB, how can I extend the disk?

**Comment by ibuildthecloud** [comment] 2015-04-25 14:29
Try

    docker run --privileged --rm -it debian:jessie resize2fs /dev/xvda1

Change xvda1 to the right disk for your setup.  We should create a system service to do this automatically on boot in AWS

**Comment by hibooboo2** [comment] 2015-04-25 14:37
+1

**Comment by bscott** [comment] 2015-04-25 22:50
rancher@ip-172-30-0-54:~$ docker run --privileged --rm -it debian:jessie resize2fs /dev/xvda1
resize2fs 1.42.12 (29-Aug-2014)
The filesystem is already 2094474 (4k) blocks long.  Nothing to do!

**Comment by ibuildthecloud** [comment] 2015-04-25 22:56
Hmmm.... Is the PV or HVM?

**Comment by bscott** [comment] 2015-04-25 23:06
HVM

**Comment by kupo24z** [comment] 2015-04-28 00:52
I'm having the same issue with a generic image on KVM/OpenStack, is it possible to mimic cloud-init's grow partition feature?

**Comment by dnegstad** [comment] 2015-04-29 16:50
I had to rebuild the partition table and reboot (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/storage_expand_partition.html) to be able to run resize2fs properly. The /dev/xvda1 partition is set to 8GB out of the box. Easiest thing to do in the short term is probably launch a fresh instance of rancher os, do the necessary partition resizing, and then take a new snapshot to use instead of the community version.

**Comment by dnegstad** [comment] 2015-04-29 16:52
[This forum post](https://forums.aws.amazon.com/thread.jspa?messageID=539484) is probably the best example of how to do the partition resize without needing to unmount your root partition.

**Comment by ibuildthecloud** [comment] 2015-04-29 23:32
@bscott We need to fix this.  So if you run PV you can just do `docker run --rm --privileged -it debian resize2fs /dev/xvda1` but HVM has a real partition table so resizing requires you to resize the partition first and then reboot.

We will look at building this resize logic into RancherOS (or simple system service that can be loaded at boot).  CoreOS does a similar thing in that they always extend their root partition on boot.

**Comment by ibuildthecloud** [comment] 2015-04-29 23:51
@bscott I got it working with no reboot needed.

@kupo24z Thanks for pointing me to cloud-init.  The following little script works.  We will try to make a more official one.

```bash
docker run --privileged -i --rm ubuntu bash << EOF
apt-get update
apt-get install -y cloud-guest-utils parted
growpart /dev/xvda 1
partprobe
resize2fs /dev/xvda1
EOF
```

**Comment by imikushin** [comment] 2015-11-30 14:43
As of v0.4.1, RancherOS AWS instance disks are resized to full size on first boot. 

The implementation relies on a magic constant (start of the state partition) and is known to work on AWS. This concern is addressed by rancher/os-images#38

**Comment by 2devnull** [comment] 2015-11-30 20:10
@imikushin - how can I get this to work on non AWS? Using ESXi.

**Comment by imikushin** [comment] 2015-12-01 05:37
@2devnull Can you try putting the following into your cloud-config?
```
#cloud-config
rancher:
  environment:
    RESIZE_DEV: /dev/your-disk
  services_include:
    resize-fs: true
    amazon-ecs-agent: true
```
Replace `/dev/your-disk` with the device with RancherOS state partition you want to resize to the full disk capacity.

**Comment by 2devnull** [comment] 2015-12-01 14:31
@imikushin - That didn't work. I used the: "ros c merge" command to add what you stated. After that, /var/lib/rancher/conf/cloud-config.yml looks like this:

```
rancher:
  environment:
    RESIZE_DEV: /dev/sda1
  services_include:
    resize-fs: true
    ubuntu-console: true
```

I then added 2 GB to the VM, but once rancherOS booted, the disk was not expanded. Unfortunately, I cannot scroll back in the ESXi console to see the messages when it was booting this VM. Is there somewhere where the boot messages are kept?

**Comment by imikushin** [comment] 2015-12-01 15:41
@2devnull Shoot! This is for v0.4.2-dev. Can you try `https://raw.githubusercontent.com/rancher/os-services/v0.4.2-dev/r/resize-fs.yml` instead of `resize-fs`?

**Comment by imikushin** [comment] 2015-12-01 15:45
@2devnull Just use the disk device in RESIZE_DEV: `/dev/sda`

So, on v0.4.1 your cloud-config should look like
```
rancher:
  environment:
    RESIZE_DEV: /dev/sda
  services_include:
    https://raw.githubusercontent.com/rancher/os-services/v0.4.2-dev/r/resize-fs.yml: true
    ubuntu-console: true
```

**Comment by 2devnull** [comment] 2015-12-01 17:04
first, doesn't "ros config" needs a delete command? I messed up and therefore had to edit the cloud-config.yml by hand. Anyway, it didn't work, the available space actually went from 5.7GB to 5.6GB, but not error this time:

![](http://imagizer.imageshack.us/v2/755x421q90/907/glEavG.png)

**Comment by deniseschannon** [comment] 2015-12-03 17:26
@2devnull Could you open a new issue for extending disk size for ESXi as well as provide more detailed instructions so we could reproduce. This issue will be used to track only for AWS.

**Comment by deniseschannon** [comment] 2015-12-03 17:44
Verified fix with v0.4.1 AMI. 

We have enabled a system-service called `aws-ec2-resizefs` which fixes the issue and is automatically enabled with v0.4.1 AMIs.

**Closed by deniseschannon** 2015-12-03 17:44 UTC
Labels: area/cloud-providers, kind/bug, status/to-test

**Comment by 2devnull** [comment] 2015-12-03 18:43
@deniseschannon - I will at a later point. Since I have a workaround for doing the resize as provided by @ibuildthecloud in this thread. I am more interested in getting #655 working at his point.

**Comment by l1a** [comment] 2015-12-27 17:38
This doesn't appear to be working in 0.4.2 AMI. Stuck back at 8G even though AWS allocated a larger disk.

**Comment by deniseschannon** [comment] 2015-12-28 23:05
@l1a Yes, this was documented in our release notes for v0.4.2 https://github.com/rancher/os/releases/tag/v0.4.2

and there is a new issue for it. https://github.com/rancher/os/issues/698

**Comment by tomreay** [comment] 2016-07-06 17:39
I'm seeing this issue again with v0.5 (AWS Image is: rancheros-v0.5.0-hvm-1 (ami-997b1eea))

I created it with 50G via the Rancher UI but only 8G is available, not sure if how to debug but happy to run anything that might help

**Comment by deniseschannon** [comment] 2016-07-06 21:28
@tomreay If you had passed in a console with your cloud config, then the resize woudln't have worked properly. 

https://github.com/rancher/os/issues/1099

**Comment by nicklucking** [comment] 2016-07-11 22:53
+1 i'm also seeing this issue same as @tomreay

**Comment by joshwget** [comment] 2016-07-11 22:56
@tomreay @nicklucking Can you post your cloud-configs? They'd be very helpful in debugging this. Thanks!

**Comment by nicklucking** [comment] 2016-07-12 05:15
@joshwget I just used the rancher UI to create the AWS hosts running rancher os. Where do I find the cloud-config?

**Comment by deniseschannon** [comment] 2016-07-12 05:27
@nicklucking Did you pass in anything in the Advanced Details -> user data section? That's the cloud-config that @joshwget is talking about.

**Comment by nicklucking** [comment] 2016-07-12 05:33
@deniseschannon I didn't should I be doing that? I'm just spinning up with the standard. Is this something I should be doing?

**Comment by deniseschannon** [comment] 2016-07-12 05:42
@nicklucking No, you shouldn't need to pass in a cloud config. It's not necessary and resize should automatically work for AWS v0.5.0. 

Can you do a `ros config export` for me?

**Comment by mccricardo** [comment] 2016-07-15 09:50
I'm seeing the same issue on AWS v0.5.0. I haven't enabled a console though cloud config.

**Comment by deniseschannon** [comment] 2016-07-15 16:01
@mccricardo We changed the way re-size works in v0.5.0. It is no longer a system-service.
http://docs.rancher.com/os/configuration/resizing-device-partition/

FYI, It is automatically set for all of our AMIs, so you shouldn't need to actually add anything in your cloud-config.

**Comment by remlabm** [comment] 2016-07-20 19:49
@deniseschannon i can confirm this is not working properly with the new AMIs.. No matter what size I set the volumes at creation, it only partitions 16gb.

source: https://github.com/rancher/os/blob/master/README.md#amazon

**Comment by mccricardo** [comment] 2016-07-21 09:16
@remlabm check issue #1099
