### ISSUE TITLE
ros os upgrade does not use local image

### ISSUE THREAD

**Issue by liyimeng** [rancher/os#898] opened 2016-04-25 12:57 UTC
Re-open https://github.com/rancher/os/issues/771 since the problem seems not fully solved, or it is coming back. 

 @deniseschannon @joshwget  I finally get some time to test the issue, I'm afraid the issue is not resolved, here is my test: 

The current version: 

<pre>[rancher@Rancher ~]$ sudo ros os version      
v0.4.4-dev 
</pre>

In the image repo:

<pre>

[rancher@Rancher ~]$ sudo system-docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
rancher/os               v0.4.4              593f2d72f0c3        10 days ago         194.3 MB
rancher/os-console       v0.4.4              9fbb7b73e2f6        10 days ago         25.37 MB
rancher/os-network       v0.4.4              83eae390036b        2 weeks ago         25.36 MB
rancher/os               v0.4.4-dev          5db090d9fec7        3 weeks ago         194.2 MB
rancher/os-udev          v0.4.4-dev          01e53502d663        5 weeks ago         25.36 MB
rancher/os-syslog        v0.4.4-dev          eab1cb99b762        5 weeks ago         25.36 MB
rancher/os-state         v0.4.4-dev          54780903c82e        5 weeks ago         25.36 MB
rancher/os-statescript   v0.4.4-dev          a9ccf1f77d84        5 weeks ago         25.36 MB
rancher/os-preload       v0.4.4-dev          29fa8d3f103a        5 weeks ago         25.36 MB
rancher/os-ntp           v0.4.4-dev          7035c8349c6a        5 weeks ago         25.36 MB
rancher/os-network       v0.4.4-dev          6b90958c06b4        5 weeks ago         25.36 MB
rancher/os-docker        v0.4.4-dev          b5708850ed54        5 weeks ago         25.36 MB
rancher/os-console       v0.4.4-dev          35dfa832d815        5 weeks ago         25.37 MB
rancher/os-acpid         v0.4.4-dev          a88965f2ab5f        5 weeks ago         25.36 MB
rancher/os-cloudinit     v0.4.4-dev          1b154b6448bd        5 weeks ago         25.36 MB
rancher/os-autoformat    v0.4.4-dev          91bcd8194c93        5 weeks ago         25.36 MB
</pre>

Try a upgrade

<pre>
[rancher@Rancher ~]$ sudo ros os upgrade -i rancher/os:v0.4.4
Pulling from rancher/os
Already exists
Already exists
Already exists
Already exists
Already exists
Already exists
Already exists
Digest: sha256:a8e119a48e5f2f1e6f757e27dfb21776ecb496c51168215e91f576314c2f5c79
Status: Image is up to date for rancher/os:v0.4.4
Upgrading to rancher/os:v0.4.4
Continue [y/N]:
</pre>

Obviously, it still try to fetch the image from Internet. If I don't have network connection, the upgrade simply fails.
I re-open the issue as a new one since sometimes dose work as expected.

**Comment by joshwget** [comment] 2016-05-06 19:39
Unfortunately, I haven't been able to reproduce this issue. I tried the following and it seems to work as expected.

```
system-docker pull busybox
system-docker tag busybox rancher/os:v0.4.4
ros os upgrade -i rancher/os:v0.4.4
```

```
Upgrading to rancher/os:v0.4.4
Continue [y/N]: y
```

Would you mind finding a sequence of steps I can use to run into this issue?

**Comment by liyimeng** [comment] 2016-05-09 09:11
@joshwget It not always happen on my node as well, but quit often. 
Instead of make a fake OS images like you did, I actually build a real os image on the master branch, them load it into system-docker, rollback & upgrade a couple of time, it them become a persistent problem for me.

**Comment by SvenDowideit** [comment] 2017-02-01 04:24
mmm, this might be related to how the upgrade code uses libcompose - so its (correctly) going to make sure that the image you specify is the same as the one on docker hub.

if you build your own os image to install, then you need to name it differently from the official `rancher/os:v0...` images - and thus it would not update the requested image name from hub.

I'm going to close this as a lot of things have changed since April last year @liyimeng please reopen if you have more information

**Closed by SvenDowideit** 2017-02-01 04:24 UTC
