### ISSUE TITLE
Add bnx2x-e2-7.13.1.0.fw to initrd

### ISSUE THREAD

**Issue by visokoo** [rancher/os#1842] opened 2017-05-09 18:26 UTC
**RancherOS Version: 0.9.0+**

**Where are you running RancherOS? baremetal, Dell PowerEdge FC430s**

Hi there, 

Is it possible to add the [bnx2x-e2-7.13.1.0.fw](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/bnx2x) file to the initrd image? I was trying to PXE boot rancheros 0.9.0 (also tried 0.9.1, all the way up to 1.0.1) but it kept failing with this error because the fw file isn't present.

> [   53.286303] time="2017-05-08T23:40:31Z" level=info msg="Running DHCP on eth1"
> [   53.447891] bnx2x 0000:01:00.0: Direct firmware load for bnx2x/bnx2x-e2-7.13.1.0.fw failed with error -2
> [   53.561926] bnx2x: [bnx2x_init_firmware:13494(eth0)]Can't load firmware file bnx2x/bnx2x-e2-7.13.1.0.fw
> [  53.674896] bnx2x: [bnx2x_func_hw_init:6003(eth0)]Error loading firmware
> [  53.755407] bnx2x: [bnx2x_nic_load:2727(eth0)]HW init failed, aborting

> cd usr/lib/firmware/bnx2x/
> bnx2x # ls -alh
> total 1.6M
> drwxr-xr-x  2 root root 4.0K May  9 01:03 .
> drwxr-xr-x 28 root root 4.0K May  9 01:00 ..
> -rw-r--r--  1 root root 149K May  9 01:00 bnx2x-e1-6.2.9.0.fw
> -rw-r--r--  1 root root 161K May  9 01:00 bnx2x-e1-7.10.51.0.fw
> -rw-r--r--  1 root root 207K May  9 01:00 bnx2x-e1h-6.2.9.0.fw
> -rw-r--r--  1 root root 169K May  9 01:00 bnx2x-e1h-7.10.51.0.fw
> -rw-r--r--  1 root root 242K May  9 01:00 bnx2x-e2-6.2.9.0.fw
> -rw-r--r--  1 root root 314K May  9 01:00 bnx2x-e2-7.10.51.0.fw

It eventually loads up to the login screen but there's no network.

I ended up having to modify the initrd image to include this fw file and it worked, but would be nicer if the default initrd image has this included already. 

Let me know if there's more info I could provide? Thanks!

**Comment by Moeser** [comment] 2017-05-09 23:16
Would it be possible to get this fix in v1.0.2?

**Comment by SvenDowideit** [comment] 2017-05-11 11:38
this should be relativly easy to do - but I really hope there's not a large number of different hardware out there >yeah right<

**Comment by SvenDowideit** [comment] 2017-05-11 11:43
interesting - some of it's already in there?

```
scripts/firmware:bnx2/bnx2-rv2p-09ax-6.0.17.fw
scripts/firmware:bnx2/bnx2-mips-09-6.2.1b.fw
scripts/firmware:bnx2/bnx2-mips-06-6.2.3.fw
scripts/firmware:bnx2/bnx2-rv2p-09-6.0.17.fw
scripts/firmware:bnx2/bnx2-rv2p-06-6.0.15.fw
scripts/firmware:bnx2x/bnx2x-e1-7.10.51.0.fw
scripts/firmware:bnx2x/bnx2x-e2-7.10.51.0.fw
scripts/firmware:bnx2x/bnx2x-e1h-7.10.51.0.fw
```

and I presume the other files are in the `kernel-extras` service?

**Comment by Moeser** [comment] 2017-05-11 20:32
I think the problem is that the kernel module (bnx2x) is now referencing the firmware, but it's not found anywhere in the initrd?  At least, this git commit to the kernel source makes it appear it was due to a change in the kernel: (note the version changes at the top).  https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/drivers/net/ethernet/broadcom/bnx2x?id=5e091e7ad0baa84a401b4dc3f859890990f0854f  the firmware we injected into the initrd which worked came from the bnx2x-e2-7.13.1.0.fw file located at  https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/bnx2x but I don't know how many of those are actively referenced in the kernel.

**Comment by SvenDowideit** [comment] 2017-05-15 02:52
https://github.com/rancher/os-kernel/pull/50

**Comment by SvenDowideit** [comment] 2017-05-16 23:57
@visokoo can you check that  https://github.com/rancher/os/releases/tag/v1.0.2-rc1 resolves this for you? I don't have hardware to test this.

**Comment by nathschmidt** [comment] 2017-05-17 00:19
@SvenDowideit, I can confirm it's working for me on a range of Dell R630's - which need the firmware too - I'd guessing it's working fine for Dell PowerEdge FC430s. Thanks!

**Comment by visokoo** [comment] 2017-05-17 00:20
@SvenDowideit, Works for me too! Thanks!

**Comment by nathschmidt** [comment] 2017-05-17 00:26
@SvenDowideit When do you think v1.0.2 will be released?

**Comment by SvenDowideit** [comment] 2017-05-17 01:27
awesome! 1.0.2 should be out within the next 7 days - there's a few more things I hope for work out, but  we'll see.

**Closed** 2017-05-17 03:34 UTC
