### ISSUE TITLE
Raspberry Pi image closed off SSH.

### ISSUE THREAD

**Issue by c-edw** [rancher/os#2528] opened 2018-10-19 18:07 UTC
**RancherOS Version: v1.4.2**
**Where are you running RancherOS? Raspberry Pi 3**

After rebooting the Pi as indicated [here](https://rancher.com/docs/os/v1.2/en/running-rancheros/server/raspberry-pi/), port 22 is closed off and I can't SSH to the Pi at all.

**Comment by niusmallnan** [comment] 2018-10-20 02:57
ping @kingsd041 , please try to reproduce when you get a chance.

**Comment by kingsd041** [comment] 2018-10-22 03:08
I cannot reproduce, here are my steps:
1. Install ros 1.4.2 into the Raspberry Pi 3
2. Adjust the default partition of docker with reference to [USING THE ENTIRE SD CARD](https://rancher.com/docs/os/v1.2/en/running-rancheros/server/raspberry-pi/#using-the-entire-sd-card)

It works fine in my environment:
```
[root@rancher ~]# ros -v
version v1.4.2 from os image rancher/os:v1.4.2
```
```
[root@rancher ~]# fdisk -l
Device         Boot   Start      End  Sectors  Size Id Type
/dev/mmcblk0p1         2048    53248    51201   25M  c W95 FAT32 (LBA)
/dev/mmcblk0p2        53249  4194303  4141055    2G 83 Linux
/dev/mmcblk0p3      4194304 30547967 26353664 12.6G 83 Linux
```
```
[root@rancher ~]# docker info | grep 'Docker Root Dir'
Docker Root Dir: /mnt/docker
```

@c-edw Can you give more detailed steps?

**Comment by c-edw** [comment] 2018-10-29 20:45
I installed Rancher OS, SSH'd on port 22, and got up to step 6 on the guide that I linked (which is a required reboot). After that, port 22 was closed off, which I verified with a `tcp -O`.

**Comment by kingsd041** [comment] 2018-11-02 06:13
@c-edw When you finish `5. sudo reboot to reboot and reload the new partition table`, port 22 will be closed after reboot?

**Comment by c-edw** [comment] 2018-11-02 13:10
Yes.

**Comment by kingsd041** [comment] 2018-11-06 03:39
@c-edw 
I tried it many times and still didn't reproduce the issue.
Can you collect some ros logs for me? You can execute this script: https://github.com/rancher/os/issues/2511

**Comment by c-edw** [comment] 2018-11-07 16:04
I won't be able to execute the script without SSH access right? If you are unable to reproduce this and it's never happened before, then I'm willing to just call this a fluke or subtle mistake on my part. What do you think?

**Comment by kingsd041** [comment] 2018-11-09 02:33
I really can't reproduce it, I suggest it be called fluke or subtle mistake

**Comment by kingsd041** [comment] 2018-12-05 06:03
Close it.
If you still have doubts, please reopen it and let me know.

**Closed by kingsd041** 2018-12-05 06:03 UTC
Labels: kind/question
