### ISSUE TITLE
Unable to change console on Raspberry Pi

### ISSUE THREAD

**Issue by distantcam** [rancher/os#1221] opened 2016-09-08 04:50 UTC
**RancherOS Version: (ros os version)**
v0.6.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Raspberry Pi 2

When trying to change the console to ubuntu I get an error because there's not enough space for the images to extract into.

```
[root@rancheros ~]# sudo ros console switch ubuntu
Switching consoles will
1. destroy the current console container
2. log you out
3. restart Docker
Continue [y/N]: y
Pulling console (rancher/os-ubuntuconsole:v0.6.0_arm)...
v0.6.0_arm: Pulling from rancher/os-ubuntuconsole

546c5e882fc5: Pull complete
d2f38a6e8021: Pull complete
0c915bdfabf6: Pull complete
b6bfcfe4f0a4: Pull complete
71ce244dca4e: Extracting [==================================================>] 69.18 MB/69.18 MB
3059e0c3e676: Download complete
16559cd40fdc: Download complete
4295ec9d4a9d: Download complete
c4857477831d: Download complete
73c0d6fd2a5a: Download complete
&{%!s(*os.file=&{2 /dev/stderr <nil>})}ERRO[0222] Failed Pulling console : Status: failed to register layer: ApplyLayer Non-zero exit code: 1 stdout:  stderr: write /usr/lib/python3.5/pydoc_data/topics.py: no space left on device, Code: 1
ERRO[0222] Failed to start: console : Status: failed to register layer: ApplyLayer Non-zero exit code: 1 stdout:  stderr: write /usr/lib/python3.5/pydoc_data/topics.py: no space left on device, Code: 1
```

I'm guessing this is because the system docker is still only using the 1Gb partition. Is there any way to expand that?

**Comment by peron** [comment] 2016-09-23 08:11
See #1084 and [Raspberry Pi](http://docs.rancher.com/os/running-rancheros/server/raspberry-pi/).
I usually use gparted right after flashing the SD-card and manually resize the partition.

**Comment by distantcam** [comment] 2016-09-23 08:17
@peron I followed the documentation to create a partition for the user-space docker, but the system-space docker is where I run out of space.

I hadn't thought to resize the partition right after the flash. That should work.

**Comment by joshwget** [comment] 2016-09-26 01:07
As @peron suggests, manually expanding the root partition after burning the SD card is the best solution for now. I think this is essentially a duplicate of #1084, so I'm going to close this.

**Closed by joshwget** 2016-09-26 01:07 UTC
