### ISSUE TITLE
Pre-packing (system-)docker images

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#719] opened 2016-01-03 07:57 UTC
Directory **/var/lib/system-docker/preload** doesn't exist and is removed during reboot. So pre-packing images as [described in the documentation](http://docs.rancher.com/os/configuration/prepacking-docker-images/)  won't work?

#706

**Comment by ryansch** [comment] 2016-02-11 20:05
Root cause here appears to be that `os-services.yml` doesn't specify `/var/lib/system-docker` as a bind mount so the `console` container can't see it.  We can create a similar directory in the `console` container but changes there won't propagate back to the host.

Should `/var/lib/system-docker` be added to `container-data-volumes` or should we move the preload location to something that can already be seen by `console`?

ping @deniseschannon

**Comment by deniseschannon** [comment] 2016-04-06 18:41
Fixed in v0.4.4-rc2

@pwfoo @ryansch If you'd like to test it out, please re-open if it's still not working.

**Closed by deniseschannon** 2016-04-06 18:41 UTC
Labels: status/to-test
