### ISSUE TITLE
NoCloud cloudinit datasource do not work

### ISSUE THREAD

**Issue by majkrzak** [rancher/os#2821] opened 2019-06-19 11:50 UTC
**RancherOS Version: (ros os version)**
v1.5.2
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

After setting 

      cloud_init:
        datasources:
        - nocloud

and rebooting rancher didn't applays any of the configs. According to the dmsg it don't even try to mount the `cidata` labelled volume :man_shrugging: 

https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html

**Comment by niusmallnan** [comment] 2019-06-20 06:35
Duplicate of #2559

**Closed by niusmallnan** 2019-06-20 06:35 UTC
