### ISSUE TITLE
Machine unreachable over SSH and network

### ISSUE THREAD

**Issue by schuylr** [rancher/os#1247] opened 2016-09-21 21:05 UTC
**RancherOS Version: (ros os version)** v0.6.0

**Where are you running RancherOS?** AWS EC2

My instances are randomly dying with no clue as to why except for a CPU spike before the failure. When the CPU usage goes back down (eventually), the host still isn't reachable by SSH or through Rancher.

![screen shot 2016-09-21 at 4 49 53 pm](https://cloud.githubusercontent.com/assets/12628715/18728514/71d2628a-801b-11e6-857b-26d64361f154.png)

![screen shot 2016-09-21 at 5 02 58 pm](https://cloud.githubusercontent.com/assets/12628715/18728879/48780ef6-801d-11e6-83c4-830a977dbf5d.png)

I haven't seen the issue with 0.6.1 yet, but if I do I'll update this issue.

**Comment by joshwget** [comment] 2016-09-21 21:09
If I had to guess, this is probably #1216.

**Comment by schuylr** [comment] 2016-09-21 21:13
@joshwget Nice. Okay, I'll make sure I'm entirely off of 0.6.0 and get to 0.6.1 ASAP. I'll reopen if this creeps back. Thanks!

**Comment by joshwget** [comment] 2016-09-21 21:13
Thanks @schuylr!

**Comment by schuylr** [comment] 2016-09-22 13:59
Hey @joshwget it's definitely happening for v0.6.1 as well. CPU is down to 10% according to AWS but the instance is completely unreachable and Rancher has identified it as "Disconnected".

System logs are similar.

**Comment by deniseschannon** [comment] 2016-09-23 02:53
@schuylr Had you started with a brand new instance or upgrade your existing ones?

Anything notable that you're doing before it happens?

**Comment by schuylr** [comment] 2016-09-23 13:13
@deniseschannon Brand new on 0.6.1

The last time, we ran a single-threaded import which basically goes through an online spreadsheet to pull data into our website database. This can take up some CPU but never crashes the server when we were using ros v0.4.5.

The most notable thing is a "spike" in CPU and various network graphs through AWS right before the failure, but I don't have any further insight due to the crashed connection. I might try a reboot next time it happens to see if I can get the connection back.

**Comment by schuylr** [comment] 2016-09-23 15:49
I tried a reboot of an instance and found that I was able to SSH in afterwards, and everything behaved like normal.

We were doing a standard Capistrano deploy to Ruby on Rails on the container at the time, likely caused by a CPU spike due to the assets precompiling on the server.

However, I must reiterate that we haven't had these issues until we bumped the versions to v0.6.0 and v0.6.1. Something about the CPU spike seems to be killing the whole server.

**Comment by jazoom** [comment] 2016-09-23 21:16
Just in case it is helpful, I'll mention here that I'm starting out with Rancher on CoreOS (I know this is an issue page for RancherOS) and I'm experiencing exactly the same thing. Everything seems to be working fine, then after a day or so Rancher is unreachable and I can no longer SSH into my server.

You linked #1216, which says it's fixed in kernel 4.4, but CoreOS is on 4.7, so maybe the issue isn't fixed?

**Comment by deniseschannon** [comment] 2016-09-23 21:30
@jazoom If you're using CoreOS, you are most likely hitting this issue.

CoreOS auto upgrades and reboots and then after reboot docker isn't running anymore.  For your hosts in disconnected state, you can log in and  do `ps -ef | grep docker` and you'll see docker isn't running. Not until you try to use docker once will it startup.  So `docker ps` will launch docker.  It's because of socket activation in systemd.

The solution is to create on systemd unit file that pings docker on boot.  Or add `docker ps` to `/etc/rc.local`

**Comment by jazoom** [comment] 2016-09-23 21:34
@deniseschannon, would that prevent me from SSH to my server?

Also, I have this in my cloud-config, which reliably starts docker and Rancher after every reboot:

`- path: /etc/systemd/system/rancher.service
    permissions: 0644
    owner: root:root
    content: |
      [Unit]
      Description=Start rancher container on system boot
      After=etcd.service
      After=docker.service

      [Service]
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/mkdir /var/lib/mysql
      ExecStartPre=-/usr/bin/docker kill rancher
      ExecStartPre=-/usr/bin/docker rm rancher
      ExecStartPre=/usr/bin/docker pull rancher/server
      ExecStart=/usr/bin/docker run --name rancher -v /var/lib/mysql:/var/lib/mysql --restart=always rancher/server
      ExecStop=/usr/bin/docker stop rancher

      [Install]
      WantedBy=multi-user.target



coreos:
  units:
    - name: rancher.service
      enable: true
      command: start`

**Comment by joshwget** [comment] 2016-09-23 22:10
@jazoom No, that shouldn't prevent you from being able to SSH into your server. But it's also a little odd that something Rancher does would be able to break SSH as well.

**Comment by jazoom** [comment] 2016-09-23 22:32
@joshwget, I agree, which is why I thought it might be related to this kernel issue.

**Comment by deniseschannon** [comment] 2016-10-05 21:52
Have you seen this happen with other OSes in Rancher?

**Comment by jazoom** [comment] 2016-10-06 06:28
I cannot remember if I tried for long enough. I decided to leave CoreOS and revisit it later when it's more stable. I've also decided Rancher might not be for me at the moment, so I didn't try another OS after this issue (which happened 3 times in a row, without fail).

**Comment by EugenMayer** [comment] 2016-10-06 14:06
Experiencing the same issue. AWS stats tell me, that the host was still up, also the uptime. So it must be either networking / ssh deamon or similar, the the host

**Comment by schuylr** [comment] 2016-10-06 18:30
@EugenMayer Since we're thinking it's the memory and specific to AWS EC2, I grabbed a Docker container for custom cloudwatch metrics and added my own changes to it. You can grab it here: https://github.com/schuylr/docker-cloudwatch-monitoring

Here's the build: https://hub.docker.com/r/schuylr/docker-cloudwatch-monitoring/

You would have to set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` in the environment variables for it to work properly. You'll find the stats under Cloudwatch > System Linux under the AWS Management interface.

**Comment by jazoom** [comment] 2016-10-06 20:59
Not specific to AWS. It happened on Vultr.

**Comment by joshwget** [comment] 2016-10-06 21:39
Does anyone experiencing this issue have access to kernel logs for one of the hosts? My current theory is that this might be related to docker/docker#5618

**Comment by schuylr** [comment] 2016-10-06 21:46
@joshwget Where are they located? I can check next time it happens after rebooting the instance.

@EugenMayer is able to reproduce it more consistently (we discussed in IRC #rancher) so he may be a better resource on this.

**Comment by joshwget** [comment] 2016-10-06 21:53
@schuylr You should be able to view them with `dmesg`.

**Comment by EugenMayer** [comment] 2016-10-07 05:18
@joshwget i looked at dmesg when the issues occurred, there was nothing, uplink and thats it, the usual last message, nothing more. Nothing in the agent.logs AFAICS - i could not find anything.

I will trigger my load tests right now to see if that happens again, yesterday, out of 5, 3 failed, but the last 2 ones were ok suddenly. Will get the dmesg output and if anything in there, paste it here

@schuylr very neat image, very handy! will try that one, on my flight right now.

**Comment by deniseschannon** [comment] 2016-10-10 06:45
@schuylr @EugenMayer What version of Rancher are you running? Also, could you try testing with a different version of Docker (like 1.10.3)? 

http://docs.rancher.com/os/configuration/switching-docker-versions/

**Comment by schuylr** [comment] 2016-10-10 12:26
I saw this very frequently on 0.6.1 and 0.6.0. I also saw it on 0.5.0. 0.4.5 was the most reliable although I have a large Dev server on 0.4.5 that seems to also disconnect when the memory is exhausted, but the containers stay up since I'm not running health checks on my Dev containers 

Can I set the system-docker with the same method you mentioned above? I'll try going back to 1.10.3

**Comment by deniseschannon** [comment] 2016-10-10 18:12
No, only user docker can be set at this point.

**Comment by joshwget** [comment] 2016-10-10 18:17
If this problem existed on v0.4.5 then there isn't any point in testing a different version of Docker. v0.4.5 used v1.10.3, so this seems independent of Docker version.

**Comment by schuylr** [comment] 2016-10-12 17:11
This may not be related to the issue, but I had a container die out from what seems to be networking errors due to exhausted memory during a Capistrano deploy. It looks like the process in my application was also eventually killed due to this memory exhaustion.

Here's the `dmesg` snippet:

```
[67914.355955] Out of memory: Kill process 31318 (utils.rb:110) score 385 or sacrifice child
[67914.360305] Killed process 31318 (utils.rb:110) total-vm:4421472kB, anon-rss:3147300kB, file-rss:0kB
[67933.188781] docker0: port 3(veth2db2756) entered disabled state
[67933.191341] veth5017ed6: renamed from eth0
[67933.250479] docker0: port 3(veth2db2756) entered disabled state
[67933.255703] device veth2db2756 left promiscuous mode
[67933.257796] docker0: port 3(veth2db2756) entered disabled state
```

And here's the resulting Memory Graph from Cloudwatch, note how there's a gap due to the network dropout however the last reported metric was 96.5% memory usage:

![screen shot 2016-10-12 at 1 08 22 pm](https://cloud.githubusercontent.com/assets/12628715/19319920/255a1bc4-907d-11e6-983b-8b84e71ed03a.png)

Does RancherOS utilize any disk swap at all, and/or is there a way to configure disk swap?

**Comment by santo74** [comment] 2017-02-13 09:39
I'm experiencing the exact same issue on my new Rancher 1.4 environment.
I have 3 servers in this environment:

Rancher server v1.4: 
- OS: RancherOS 0.7.1
- RAM: 2GB

App server:
- OS: RancherOS 0.7.1
- RAM: 2GB

DB server:
- OS: RancherOS 0.7.1
- RAM: 1GB

The DB server image has the ssh/disconnection issues as described in this topic. The other 2 have no issues.
Even when I stop the DB software on the DB server image, the issue occurs after several hours.
However, If I set the DB server node to inactive in Rancher and then stop all docker containers on the node it keeps running.
So it might be related to Rancher v1.4 in combination with "low memory" nodes?

FYI: I have a similar environment but with Rancher v1.1.4 where the issue doesn't occur.

So I have the impression that the described issues are related to the version of Rancher server and not RancherOS

**Closed** 2018-12-18 03:38 UTC
