### ISSUE TITLE
system-dockerd: segfault.

### ISSUE THREAD

**Issue by Magicloud** [rancher/os#2796] opened 2019-06-01 06:50 UTC
**RancherOS Version: (ros os version)**
v1.5.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Baremetal (HP ProLiant DL380 G7)

While upping zfs service, I got segfault. It occurred at:
```
zfs_1 | Status: Downloaded newer image for rancher/os-headers:4.14.122-rancher
zfs_1 | + ros service up kernel-headers-system-docker
zfs_1 | time="2019-06-01T06:43:34Z" level=info msg="Project [os]: Starting project " 
zfs_1 | time="2019-06-01T06:43:35Z" level=info msg="[0/21] [kernel-headers-system-docker]: Starting " 

Message from syslogd@rancher at Jun  1 06:43:40 ...
 kernel:[ 2966.538308] system-dockerd[1]: segfault at 8 ip 0000000000541d26 sp 000000c420cf9308 error 4 in system-dockerd[400000+1486000]
zfs_1 | time="2019-06-01T06:44:39Z" level=info msg="[1/21] [kernel-headers-system-docker]: Started " 
zfs_1 | time="2019-06-01T06:44:39Z" level=info msg="Project [os]: Project started "
```
In dmesg, it is at
```
[ 2966.171351] IPv6: ADDRCONF(NETDEV_UP): vethbf9679b: link is not ready
[ 2966.538308] system-dockerd[1]: segfault at 8 ip 0000000000541d26 sp 000000c420cf9308 error 4 in system-dockerd[400000+1486000]
[ 2966.538834] eth0: renamed from vethe222bc9
```

**Comment by niusmallnan** [comment] 2019-06-01 14:04
Duplicate of #2484
See this comment https://github.com/rancher/os/issues/2484#issuecomment-445088750

**Closed by niusmallnan** 2019-06-01 14:04 UTC
