### ISSUE TITLE
Problem w/install of latest v0.8.0 -rc10

### ISSUE THREAD

**Issue by mcparland** [rancher/os#1591] opened 2017-02-09 20:21 UTC
**RancherOS Version: (ros os version)**
v0.8.0-rc10

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal: INtel NUC i3 w/32 GB ram, 500GB ssd.

Just tried install of latest rc from ISO flash drive. 
Boot from ISO appears to work fine.

[rancher@rancher ~]$ 
[rancher@rancher ~]$ sudo ros install -c cloud-config.yml -d /dev/sda
> INFO[0000] No install type specified...defaulting to generic 
Installing from rancher/os:v0.8.0-rc10
Continue [y/N]: y
> INFO[0004] user specified to install pre v0.8.0: rancher/os:v0.8.0-rc10 
> INFO[0004] starting installer container for rancher/os:v0.8.0-rc10 
set-disk-partitions deprecated
Installing from :v0.8.0-rc10
> time="2017-02-09T19:53:51Z" level=info msg="start !isoinstallerloaded" 
> time="2017-02-09T19:53:51Z" level=info msg="ps error: exit status 1" 
> time="2017-02-09T19:53:51Z" level=error msg="error setDiskpartitions exit status 1" 
> time="2017-02-09T19:53:51Z" level=fatal msg="Failed to run install" err="exit status 1" 
> FATA[0004] Failed to run install                         err="exit status 1"
[rancher@rancher ~]$ 

Note, previous install of 0.7.1 worked fine but had console problems (ref issue #1566

**Comment by deniseschannon** [comment] 2017-02-09 21:08
Confirmed that this is happening.

**Comment by SvenDowideit** [comment] 2017-02-10 00:57
oh joy - it seems that semver & hashicorp sort the `-rcXX` meta alphabetically, so `-rc10` is not greater than `-rc3`

I'm switching to the version code that @joshwget made for the catalog, as it handles what people _do_ rather than what the spec says.

**Comment by SvenDowideit** [comment] 2017-02-10 01:18
#1593 fixes this for me :)

**Comment by SvenDowideit** [comment] 2017-02-10 12:29
I'm building an v0.8.0-rc11 just to make sure that the library update to replace the semver library with a logical versioning GreaterThan works out.

clearly, nothing can go wrong :)

**Comment by mcparland** [comment] 2017-02-13 03:43
Well, I can boot up rc11 from flash ISO and do a ros install to the ssd.  I confirmed, prior to
reboot that cloud-config.yml gets copied to ssd as usr-config(sp?).  But, after reboot
that config file no longer works (it did on the 7.1 install).  System comes up as DHCP with
the wrong domain name.  Cloud-config.yml is:
>>>>>>>>>>>>>>>>>>>>>>>>>
#cloud-config

hostname: electra.rtisys.org

rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 192.168.1.30/24
        gateway: 192.168.1.1
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4

ssh-authorized-keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDESEL1x/nFAJY0b4ejsuv5**** deleted on purpose ********
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Also, back to where this all started w/7.1,  I cannot login from either console or remote ssh.  The remote ssh
makes sense because ranchos does not like the cloud-config.yml that I gave it.  But console requires a login
(where the ISO does not) and will not accept either my previously set passwd from the ISO boot or the default "rancher".  Any ideas?
Can probe around  a bit, but will need some pointers to do that.

Regrds,
rtisys

**Comment by SvenDowideit** [comment] 2017-02-13 04:19
@mcparland mmm, that's surprising - I just copied your cloud-config.yml, and used it to install, and I get the hostname, and the IP address

(though this is on a machine with only one network)

I was wondering if the newlines or something else was going on.

**Comment by mcparland** [comment] 2017-02-13 18:03
Thanks for checking,.....will re-enter the config more carefully.  It would be easier
if I could get into the machine after the reboot.  Never succeeded in getting
Grub's attention during boot. (left shift A or something like that?)  Is there a way
to get into grub after boot to set up kernel params for following boot?

Will keep googling this, but results seem contradictory (this always works, that
seems to work every fifth time, don't bother trying that. etc. )
If you know of something that works, would appreciate
a heads up. 

Cheers,
rtisys

**Comment by SvenDowideit** [comment] 2017-02-13 18:18
oh - v0.8.0 has replaced grub with syslinux - I basically just keep tapping the `a` key to get to it.

**Comment by kapolos** [comment] 2017-03-29 01:20
Same issue with `v.0.9.1`. Installing `v0.7.1` worked with no hick-ups.

![image](https://cloud.githubusercontent.com/assets/10794126/24434239/06cd8bee-1437-11e7-9c13-72708bfa26d4.png)

![image](https://cloud.githubusercontent.com/assets/10794126/24434220/e8a03036-1436-11e7-9ed7-20f7d5e630af.png)

![image](https://cloud.githubusercontent.com/assets/10794126/24434229/f14d8012-1436-11e7-95cc-0e828c4f33d2.png)

**Comment by capnslipp** [comment] 2017-07-20 00:30
Having the same issue as @kapolos.  First time Rancher user.  Just trying to get this thing installed in a local VM.

Booted off the the iso fine and figured out how to set both root & rancher passwords to blank and to let sshd permit blank passwords _(for the temporary in-memory ISO-booted rancher OS, mind you; I would never do this to an installed OS)_, so I can install using my machine's native terminal app and get the ssh pub key into the `cloud-config.yml` an all that.

After setting up the `cloud-config.yml` (passes validation) and formatting my main drive disk-image, ran `ros install -c cloud-config.yml -d /dev/sda1`.

Received status messages and errors nearly matching @kapolos's:

~~~
[root@rancher ~]# ros install -c cloud-config.yml -d /dev/sda1 
> INFO[0000] No install type specified...defaulting to generic 
Installing from rancher/os:v1.0.3
Continue [y/N]: y
> INFO[0001] start !isoinstallerloaded                    
> INFO[0001] trying to load /bootiso/rancheros/installer.tar.gz 
> INFO[0002] Loaded images from /bootiso/rancheros/installer.tar.gz 
> INFO[0002] starting installer container for rancher/os-installer:latest (new) 
Installing from rancher/os-installer:latest
> time="2017-07-20T00:19:30Z" level=error msg="partprobe error exit status 1" 
> time="2017-07-20T00:19:30Z" level=error msg="error setDiskpartitions exit status 1" 
> time="2017-07-20T00:19:30Z" level=fatal msg="Failed to run install" err="exit status 1" 
> FATA[0002] Failed to run install                         err="exit status 1"
~~~

**Comment by capnslipp** [comment] 2017-07-20 00:37
Scratch that; I just realized that RancherOS docs's Installing RancherOS to Disk instructions, you're installing to `/dev/sda`, not `/dev/sda1`.  Worked when changed it to specify the former rather than the latter.

**Comment by SvenDowideit** [comment] 2017-07-20 23:24
I'm going to close this issue - it was for a specific issue where the version number parsing failed to consider `rc10` to be after `rc9` because it used non-numerical ordering

**Closed by SvenDowideit** 2017-07-20 23:24 UTC
Labels: kind/bug
