### ISSUE TITLE
Boot hangs on: ros-sysinit:fatal: Error response from daemon: mount already exists with name

### ISSUE THREAD

**Issue by riktam** [rancher/os#2679] opened 2019-02-16 10:32 UTC
RancherOS Version: 1.5.1 on Raspberry Pi 3 Model B

1) Install fresh image into a SD cards.
2) login as rancher and reboot 3 times 

On the third restart the boot process it will hang with the error :
ros-sysinit:fatal: Error response from daemon: mount already exists with name

There are other previous errors:
ros-sysinit:error: Failed to start: all-volumes : Error response from daemon: mount already exists with name

**Comment by niusmallnan** [comment] 2019-02-17 00:46
Duplicate of #2674
You can try v1.4.3. The bootup speed of v1.4.3 is slow, but this problem rarely occurs.

**Closed** 2019-02-21 10:15 UTC
