### ISSUE TITLE
iPXE boot doesn't load cloud-config (DHCP based DNS is not being used)

### ISSUE THREAD

**Issue by gizmotronic** [rancher/os#1790] opened 2017-04-17 01:31 UTC
**RancherOS Version: (ros os version)**
0.9.2-rc2 and later

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
vSphere Hypervisor 6.5.0 (ESXi) virtual machine, iPXE, diskless

RancherOS loads on a diskless VM using iPXE, but starting with 0.9.2-rc2, it's unable to load the cloud-config specified using the rancher.cloud_init.datasources kernel command line parameter.

I've isolated the problem to changeset 79a7e59. Reverting this change allows 1.0.0 to work normally.

**Comment by SvenDowideit** [comment] 2017-04-17 19:20
oh wonderful - that change was made to fix AWS cloud-init.

**Comment by SvenDowideit** [comment] 2017-04-17 19:22
@gizmotronic - can you post the log file of boot with `rancher.debug=true`? I'm curious to see what's going on.

**Comment by gizmotronic** [comment] 2017-04-18 03:53
@SvenDowideit It took me a bit to figure out how to get past the rate limited printk, but here it is: [rancheros-dmesg.txt](https://github.com/rancher/os/files/927258/rancheros-dmesg.txt)

This was really helpful. My cloud-config can't load because the host it's coming from is on my internal network, which can't be resolved by Google DNS. I don't expect it to be using Google because my DHCP server is providing the necessary (private) DNS configuration.

In case some future reader is wondering how I turned off the rate limiting, I added ```printk.devkmsg=on``` to my kernel command line parameters.

**Comment by SvenDowideit** [comment] 2017-04-18 14:09
yes, that's not good. can you add your local dns server seting to the boot cmdline for now?

**Comment by SvenDowideit** [comment] 2017-04-18 14:44
this might be the root cause of something I'm trcking down atm - thank you for the analysis

**Comment by gizmotronic** [comment] 2017-04-18 18:27
I've confirmed that setting the local DNS server is an effective workaround.

**Comment by SvenDowideit** [comment] 2017-05-17 04:58
argh! it works for my server (on an installed disk), guess I need to kick it with pxe-dust

```
[root@rancher rancher]# cat /etc/resolv.conf 
# Generated by dhcpcd from eth0.dhcp, eth1.dhcp
# /etc/resolv.conf.head can replace this line
domain home.org.au
nameserver 10.10.10.1
nameserver 8.8.8.8
# /etc/resolv.conf.tail can replace this line
[root@rancher rancher]# ros -v
ros version v1.0.1
[root@rancher rancher]# system-docker exec -it network dhcpcd -U eth0
broadcast_address=10.10.10.255
dhcp_lease_time=864000
dhcp_message_type=5
dhcp_server_identifier=10.10.10.1
domain_name=home.org.au
domain_name_servers='10.10.10.1 8.8.8.8'
ip_address=10.10.10.2
network_number=10.10.10.0
routers=10.10.10.1
subnet_cidr=24
subnet_mask=255.255.255.0
eth0: dhcp6_dump: No such file or directory
```

**Comment by SvenDowideit** [comment] 2017-05-17 05:05
yup, and the dns servers are also set and working at cloud-init-save when I pixieboot it with a local dns only datasource url :(

**Comment by SvenDowideit** [comment] 2017-05-17 05:09
@gizmotronic I guess the next question is - what do oyu get when you run `system-docker exec -it network dhcpcd -U eth0`

**Comment by gizmotronic** [comment] 2017-05-20 03:34
The VM I'm using (typical of my environment) is diskless. The problem doesn't happen when a disk is attached, whether with a local install or used as a state partition.

I'm readily able to reproduce the problem with v1.0.0, but it appears to be resolved in v1.0.1. I've just booted v1.0.1 with 6 different configurations and had no trouble with any of them. I was also able to build and boot ToT without any trouble.

Any ideas on what might have changed to fix this?

**Comment by SvenDowideit** [comment] 2017-06-14 05:22
we think there's a race condition when there's a delay in the DHCP - but so far, its all theories - I can't manage to make it happen.

**Comment by SvenDowideit** [comment] 2017-06-19 05:04
@gizmotronic I made a test build with https://github.com/rancher/os/pull/1921 in it - see https://github.com/rancher/os/releases/tag/v1.1.0-test1

is there any chance you could see if this also solves your problem?

**Comment by gizmotronic** [comment] 2017-06-21 07:16
I had no trouble booting v1.1.0-test1 in my test VM.

**Comment by liyimeng** [comment] 2017-06-28 09:20
Thanks @SvenDowideit  I have hit on the same problem, you test build solve the problem. Could we release this asap?

**Comment by SvenDowideit** [comment] 2017-06-28 11:50
Have you tried v1.0.3? It contains one part of the 1.1.0 test changes.
The other needs a bit more testing as its more intrusive

**Comment by SvenDowideit** [comment] 2017-06-29 12:53
I'm hoping this will be r

esolved by #1921

**Comment by liyimeng** [comment] 2017-06-29 19:40
I guess I did, only 1.1.0 works.  But I could double check when in office tomorrow.

**Comment by liyimeng** [comment] 2017-06-30 11:34
I run my test again, using https://releases.rancher.com/os/latest/vmlinuz 
It seems work, cloud-config is applied. 
 However, after boot, it always shows the version as RancherOS v1.0.2, Not v.1.0.3!

**Comment by liyimeng** [comment] 2017-06-30 12:07
Sorry, my fault! I have an disk attach to my machine, and it is format with RANCHER_STATE. It stores the config I loaded early!

New test shows: **only v1.1.0-test work**!

**Comment by liyimeng** [comment] 2017-06-30 12:18
Even v1.1.0-test is no more working. :(

**Comment by SvenDowideit** [comment] 2017-08-02 01:08
https://github.com/rancher/os/pull/1921 backported to v1.0.4 too

**Comment by liyimeng** [comment] 2017-08-23 12:14
Hi @SvenDowideit I run v1.04. This is still not working.  Here is my boot script
<pre>
#!ipxe

set base-url http://10.10.10.1:8000
kernel ${base-url}/vmlinuz rancher.autologin=tty1 rancher.state.dev=LABEL=RANCHER_STATE rancher.state.autoformat=[/dev/sda,/dev/vda] rancher.cloud_init.datasources=[url:${base-url}/cloud-config]
initrd ${.base-url}/initrd

</pre>
<pre>
[rancher@rancher ~]$ sudo ros config export
EXTRA_CMDLINE: /init
rancher:
  autologin: tty1
  cloud_init:
    datasources:
    - url:http://10.10.10.1:8000/cloud-config
  environment:
    EXTRA_CMDLINE: /init
  state:
    autoformat:
    - /dev/sda
    - /dev/vda
    dev: LABEL=RANCHER_STATE
ssh_authorized_keys: []


[rancher@rancher ~]$ wget  http://10.10.10.1:8000/cloud-config
Connecting to 10.10.10.1:8000 (10.10.10.1:8000)
cloud-config         100% |*************************************************************************************************************|   531   0:00:00 ETA

[rancher@rancher ~]$ cat cloud-config 

#cloud-config

hostname: host-119

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbw3HEUCApEnStLH5NibRhP6KipG3l8ENCdXTBnDzQ51dUsD/sVgEIA1OwJUcEcNWCgSbnP7GE7hdsRfySNUjNcGDEIv70uR59b0r/nJ6ySgAcRL9RlvuiW/Vas7ZUS6JW/8uOVrb1D32Z0pV804nAU4Afym3NiIpH9GqSZMg9Etge764pT8aiWMx1RKl8UiYznIuBnT/gzWGOnm+s/udRAx9g8xAYd67Gzw4H05RlnR/3yHOdMTXJhlcovsDOpoKBEsG+MmM2W/S9G/ia84zbfWkUSI7bLy+UxMs6nJEAYCr66JWTr+EB4IpOYmiu5H6cyuZhSTy9QnHRGigv6RUP liyi.meng@ericsson.com
rancher:
  network:
    interfaces:
      eth0:
        dhcp: true[rancher@rancher ~]$ 
</pre>

**Comment by liyimeng** [comment] 2017-08-23 12:16
@SvenDowideit BTW, for a personal question, are you the only guy work on RancherOS now? :)

**Comment by SvenDowideit** [comment] 2017-08-30 04:18
I just re-did the handling of resolve.conf during boot, it should make dhcp based DNS much more functional

it'll be released in v1.1.0 (ga) this week.

**Closed** 2017-09-05 00:48 UTC
Labels: area/boot, BACKPORTED, kind/bug, status/to-test

**Comment by gizmotronic** [comment] 2017-09-05 02:21
This has resolved the issue for me. I was having trouble with v1.0.4 late last week but v1.1.0 boots without issue. Thank you!

**Comment by liyimeng** [comment] 2017-09-06 11:26
This is still not working if you have more than one interface on your machine. To reproduce, create a KVM VM with two interfaces, pxe boot  from one of the interface. In case you also have another dhcp server running on another interface, it is almost 100% fails.  I will propose RancherOS add another kernel parameter to indicate from which interface that the iPXE boot is supposed to happen.

**Comment by SvenDowideit** [comment] 2017-09-14 03:44
@liyimeng can you please raise a new issue for that - I keep forgetting that there's an extra problem
