### ISSUE TITLE
Latest rancherOS ISO freeze at boot time on virtualbox

### ISSUE THREAD

**Issue by ArKam** [rancher/os#389] opened 2015-06-15 19:45 UTC
Hi guys,

I'm currently setting up a RancherOS host on VBox v4.3.28 from the latest RancherOS iso available on your website https://releases.rancher.com/os/latest/rancheros.iso (v0.3.1) at this time.

I do want to setup this host for a demo of what RancherOS can achieve and how it could help us to renew our production infrastructure (around 100 hosts from AWS and BareMetal).

However, I'm facing a quite strange error involving 9Pnet device.
After installing the iso to /dev/sda everything seems OK and rancherOS ask for reboot.
Once rebooted the host hang indefinitely with the following statement:

**9pnet: Could not find request transport: virtio.**

the used cloud-config.yml is available at the following URL: https://github.com/ArKam/seed/blob/master/cloud-config.yml

So, could you help me regarding this error?

**Comment by imikushin** [comment] 2015-06-16 06:51
I'll look into this.

**Comment by ArKam** [comment] 2015-06-16 12:45
Thanks a lot, for information, I've disable Sound and USB Port/channels, the used storage controller is a SATA controller and have been tested with SAS with the same error.

My network adapter is an Intel PRO/1000 T Server in bridge mode.

**Comment by ArKam** [comment] 2015-06-17 13:11
I tried to create a new VM on virtualbox using the script provided at https://github.com/rancherio/os/blob/master/scripts/build-vbox-vm
I've got the exact same issue.

For information I'm running VBox on a Mac OS X 10.10

**Comment by Xe** [comment] 2015-06-17 18:07
I ran into this last night. Wait about 30 seconds and it will resolve itself.

**Comment by ArKam** [comment] 2015-06-18 11:18
nop, still hanging after 15 minutes waiting in front of the VM.

**Comment by imikushin** [comment] 2015-06-18 13:49
@ArKam sorry for delay with this issue. What are the exact steps to reproduce? 
I'm using the latest OS X (10.10.3) and VirtualBox (4.3.28) and can't see any problem running RancherOS v0.3.1. 

Also, you might want to use "virtio" network adapters (instead of "Intel PRO/1000 T Server") in VirtualBox: they are faster because there's no hardware to emulate.

**Comment by ArKam** [comment] 2015-06-18 15:47
Hi @imikushin , ok so I'm running VBox 4.3.28 on a Mac OSX 10.10.4 and I've migrate to the virtio driver.

The process is pretty simple, download the v0.3.1 iso (or latest at this time).
Create a VM on VBox using your recommandation (USB port Disable, Sound Disable, Virtio driver for network interface).
Start the VM with the ISO as boot device.
execute: sudo rancheros-install -c ./cloud-init.yml -d /dev/sda
Wait for completion.
Eject the ISO.
sudo reboot.
Wait for ever alone :D

**Comment by imikushin** [comment] 2015-06-18 15:58
Okay. I repeated these steps and actually saw the message about 9pnet. But
my VM isn't blocked. Can you ping the VM IP address? And try to ssh into
it. Use hostonly network with DHCP.

**Comment by ArKam** [comment] 2015-06-19 07:20
@imikushin , I'm really sorry, but even with the hostonly network selected as network method, I'm still hanging indefinitely on the 9pnet message.
Do you want I push you my VM ?

**Comment by imikushin** [comment] 2015-06-19 10:47
Sure. Just give me a URL where I can get it. You can export the VM in
virtualbox to an archived format.

**Comment by ArKam** [comment] 2015-06-19 18:11
OK, many thanks here is the OVA: https://github.com/ArKam/issues/blob/master/rancheros.ova

**Comment by faisyl** [comment] 2015-07-03 06:26
Is this because it's waiting for the ubuntu console to download ? I ran into the same problem when I first tried it on a bandwidth constrained VM install.

**Comment by ArKam** [comment] 2015-07-03 22:25
well, I've not set any bandwith restriction and I'm using a 10GBps/10GBps link as we do have huge internet access at work, so it doesn't seems to be the same issue as you.

**Comment by imikushin** [comment] 2015-07-06 07:05
@ArKam We've released RancherOS v0.3.3 recently. Can you check if you're still experiencing the issue with RancherOS v0.3.3? If this is still the case, can you attach your exported VM for me to check?

**Comment by ArKam** [comment] 2015-07-06 20:51
No problems, I'll do it tomorrow morning ;-)

**Comment by jest** [comment] 2015-07-07 12:44
I have the same problem as OP, but running 0.3.3 under ESXi 6.0. What is interesting, the machine is available on the network (can be pinged), but SSH is not available

**Comment by deniseschannon** [comment] 2015-07-08 17:21
@jest Did you run `rancheros-install` before trying to ssh in? 

http://os.docs.rancher.com/docs/running-rancheros/server/install-to-disk/

**Comment by jest** [comment] 2015-07-09 08:27
Of course, everything as in the manual.

In the end I managed to run the installed RancherOS, so it is not related to VMWare: 9p warnings are still reported, but everything works.

I'll investigate more; the next suspect is cloud-config

**Comment by jest** [comment] 2015-07-09 09:37
I'm sorry, I cannot recreate the problem. I can only assure you that there was some problem; at the end I suspect some strange combination of parameters of virtual machine (unfortunately I have removed the original problematic VM...)

**Comment by ArKam** [comment] 2015-07-10 22:08
Ok, so sorry for the late, but I'm quite buzzy those days :D - Well, you'll find an updated version of the VM (Complete recreation using latest version) hanging at the exact same moment.

https://github.com/ArKam/issues/blob/master/rancheros-0.3.3.ova

**Comment by Bhlowe** [comment] 2015-07-18 18:59
I'm seeing this on my ESXI 5.5.0. Booting from the rancheros.iso with an unformatted drive worked fine. 
I ran rancheros-install using a simple cloud-config (1 pub key only, no network settings as I wanted dhcp.)

Once the new (bad) install is on the disk, I can't boot back into the virtual CD based rancher.iso file. So I can't change the install options to try to reinstall a different version or network setup.

**Comment by jest** [comment] 2015-07-20 06:34
@Bhlowe If you want to boot from CD while having bootable HD, you have to change the order of booting devices in virtual BIOS. Depending on vmWare client you should see an option like "Enter BIOS after boot" somewhere.

**Comment by Bhlowe** [comment] 2015-07-20 16:13
Thanks Jest, figured that out (boot options menu in esxi) but..  still unable to get rancheros boot past that 9pnet: Could not find request transport: virtio message. 
I have installed CoreOS from iso so my machine isn't completely weird. 
I can let anyone see this via teamviewer if anyone wants to debug.

- Brad

**Comment by pl33g0r** [comment] 2015-07-21 02:04
Having the same issue while running everything on bare metal...

**Comment by 5m1l3** [comment] 2015-07-25 23:42
+1 Have same issue on bare metal after installation.
But livecd iso running fine.

**Comment by 5m1l3** [comment] 2015-07-26 00:05
I found this thread https://lists.gnu.org/archive/html/qemu-devel/2014-02/msg01330.html
I unpack initramfs from current rancheros, and i think adding 9pnet_virtio to it, can solve this trouble.

**Comment by valqk** [comment] 2015-07-30 08:55
I've had the same problem with Virtualbox.
I have found where it came from in my case. It turned out that if I add user from cloud-config file I get virtio error.
Actually it's just that booting hangs to this last error. When working I still get it, but afterwards I see the login.
If I just have hostname and ssh-keys only, the installed os works ok.

**Comment by deniseschannon** [comment] 2015-07-30 16:22
@valqk Currently RancherOS doesn't support adding in users into the cloud config file. I've tried to add some notes into our documentation to make it more apparent that it's not supported. We are looking to add in users  and have an issue open to track it: https://github.com/rancher/os/issues/263

**Comment by Bhlowe** [comment] 2015-07-30 16:34
I tried again with a simple cloud-config.yml that just had ssh keys and hostname and it failed the same way. I think @5m1l3 is on the right track about adding 9pnet_virtio to the initramfs, repack, and retry.

**Comment by ArKam** [comment] 2015-07-30 16:58
This is not an issue regarding the users as I don't have any on it, but as you pointed it out, it MAY be a problem regarding Cloud-init waiting infinitely from it latest error.

I'll check to install it without cloud-config file and see if the problem is back.

**Comment by valqk** [comment] 2015-07-30 18:46
@deniseschannon - yeah I've noticed after that and that's why removed users from it. Just notified how I 've fixed my issue. Though I'm still getting the virtio error, but afterwards I get login prompt.

**Comment by ArKam** [comment] 2015-08-12 06:40
Any news regarding this bug? Regarding the fact that it is reproducible by customers on bare-metal installation, it should be one of your top priority as it deeply impact the way new potential customers will advocate or not for your product.

**Comment by Bhlowe** [comment] 2015-08-12 11:26
I'm happy to test if someone knows how to add 9pnet_virtio and repackage. That should do the trick. 

Brad

**Comment by kpelt** [comment] 2015-08-12 18:23
This is still an issue as I have tried a ton of different installs with no dice.  I am on ESXi 6 running hardware version 9 with minimal cloud-config.yml file.

**Comment by ibuildthecloud** [comment] 2015-08-12 18:40
Sorry if it seems like we aren't working on this issue.  We are about to release RancherOS v0.4 which is a major change to address a lot of the usability concerns of RancherOS.  One big problem is that when startup fails there is very little information printed such that it's quite hard to troubleshoot.  There is a plethora of root causes that could be causing all of the issues listed and in most situations the 9p error message is completely unrelated.

@kpelt You said you have seen this issue on tons of different installations.  What is the easiest way to reproduce it?  Do you see this in VMware Desktop/Fusion by chance?

**Comment by kpelt** [comment] 2015-08-12 18:44
I mean basically like I am insane, "doing the same things over and over again expecting a different result", with minor changes each time.  I am only doing this in a lab with ESXi on HP blades running vSphere 6.  I have not tried it on other installations because my end goal is to have it inside my lab where I can build out much more functionality in the future.

**Comment by kpelt** [comment] 2015-08-12 19:17
I'll have to use another OS for the time being because I don't want to build on top of something that on reboot could wipe me out.  I'll just wait for the next version.

**Comment by imikushin** [comment] 2015-08-13 18:38
I think I might know what was causing the freeze: I've been playing with @ArKam's OVA (thanks @ArKam and sorry for the unthinkable delay with this) and tried to use it with rancheros.iso "inserted": this way, the OS boots from the ISO, but uses the virtual HDD as the state drive. 

One thing that's lost after installing to HDD is the log messages of services going up. Looks like the error messages are gone for good, too. While booting with the ISO installed I can see that 'cloud-init-pre' and 'cloud-init' fail to run (exit with status code 1).

**Comment by imikushin** [comment] 2015-08-13 18:40
Also, what cloud-config are you using to install RancherOS? That might help find the root cause of this.

**Comment by ArKam** [comment] 2015-08-13 18:42
@ibuildthecloud, I'm really pleased to hear you back on this topic as I personally really put a large amount of optimism on your platform !

How can we help you to solve this issue ? I've provided my VM twice and can do it again if needed.

**Comment by imikushin** [comment] 2015-08-13 18:46
@ArKam Can you please provide the cloud-config that you used with `rancheros-install`?

**Comment by ArKam** [comment] 2015-08-13 18:46
@imikushin \o/ Glad I could help and that I hear you back too!! I know that you guys are working hard and we are in the middle of the summer time, this is why I don't ping earlier. Anyway, thanks a lot for those informations, I'll give you my cloud-config file as soon as I'll be back home.

**Comment by ArKam** [comment] 2015-08-19 09:14
@imikushin Hi, here is the cloud-config file: https://github.com/ArKam/seed/blob/master/cloud-config-rancheros.yml

**Comment by imikushin** [comment] 2015-09-15 05:44
Sorry for not commenting on this thread for so long. 

The issue was caused by failing to boot with incorrect cloud-config. RancherOS should have at least ignored the incorrect cloud-config, but continue to boot anyway, so that behaviour was clearly wrong.

I'm finally pleased to announce that this issue fixed in v0.4.0 and the release is going to be out very soon - hopefully, this week. 

Thanks everyone and personally @ArKam for providing feedback and for your patience.

**Closed by imikushin** 2015-09-15 05:44 UTC
Labels: area/boot, kind/bug

**Comment by ArKam** [comment] 2015-09-17 22:30
Thanks a lot to the rancheros team for your dedication and  the way you worked on this issue. It may have been a little long sometime but the result worst the waiting ;-)

**Comment by mbettan** [comment] 2015-10-17 00:03
I have exactly the same issue with ESXi 5.5 and rancherOS 0.3.3

Below is my cloud init file, any idea why?
```
#cloud-config
ssh_authorized_keys:
  - ssh-rsa 
AAAAB3NzaC1yc2EAAAABJQAAAQEAkly0yQzYjKaq8QpMgR9vq+zn2ibmiT55DONn
HSKxqLhSgWa0r4/xLm5Hb/KsbnPYzXejiuRD7Wkn9qSVrI/b/D1xDcBy6CZ9qifG
Gr724pIuuL/9OmKYT+WJNUTdRR2iPczvwwOyH5eXf8A4wLc9jaAF6cYlRanCkgYf
XlBXCmcVmctzdyH5aw/aqr4Rqy0K5MdEferc7RlYE25WAg9oYv6NWhBn2VFvyZ2N
0+OfDU1rQE7ZxIZLTMKYi/xUIjenkLC8BtEkxqW1zCSmU/LUC0jGBFAtJINBbCAa
OJbx8WKk+QBxxTOl9jp9dLp5xpKdQemrkp7nBdEd/WGMKBaf7Q

rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 172.16.1.200/16
        gateway: 172.16.1.1
        mtu: 1500
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4

hostname: rancher
```

**Comment by ibuildthecloud** [comment] 2015-10-17 00:35
@mbettan We are right on the heels of releasing v0.4.  Do you want to try [v0.4-rc11](https://github.com/rancher/os/releases/tag/v0.4.0-rc11) and see if it works?

**Comment by mbettan** [comment] 2015-10-17 01:05
![screenshoterror](https://cloud.githubusercontent.com/assets/14251830/10556134/e6209500-747b-11e5-887f-1d616dd726a6.png)

Not working with 0.4-rc11

**Comment by ibuildthecloud** [comment] 2015-10-17 01:15
okay.  Have you by chance tried vmware desktop?  just curious if that fails too.  It will take a bit longer to validate ESXi because we don't have an environment handy.  But I believe I can deploy ESXi in VMware Desktop

**Comment by mbettan** [comment] 2015-10-17 01:19
No, I didn't try as we would like to POC rancherOS within ESXi Clusters for this project.

Most of your future users will use ESXi hypervisors (or Hyper-V / KVM). People using VMware workstation it's only for testing locally.

**Comment by mbettan** [comment] 2015-10-17 01:19
Do you think the issue is my cloud-init or ESXi 5.5 hypervisors not fully working at this time?

**Comment by infinitysgame** [comment] 2015-10-18 21:20
I'm experiencing the same behaviour. Install completes without error.

VMware ESXi 5.5 U3.
My [cloud-config.yml](https://gist.github.com/infinitysgame/aaf221715dad5fd701e4) file.

**v0.3.3** (hangs indefinitely) 
![rancheros-v0 3 3-fail-esxi-5 5](https://cloud.githubusercontent.com/assets/12916656/10566644/231ecb38-75e5-11e5-89e1-1dcb41c1df2d.png)

**v0.4.0-rc11** (stuck in a reboot loop)
![rancheros-v0 4 0-rc11-fail-esxi-5 5](https://cloud.githubusercontent.com/assets/12916656/10566653/5d9b4b74-75e5-11e5-8aec-b5db17020522.png)

**Comment by 2devnull** [comment] 2015-10-19 23:37
same issue here. ESXi 6

![ramcheros-9p](https://cloud.githubusercontent.com/assets/4563854/10594165/52a168e4-7698-11e5-8a2c-1a664dfa70b2.png)

Ping works, but ssh doesn't. I am really surprised to know that the team developing this have not tested on ESXi. That and other hypervisor is where the market is at.

**Comment by ibuildthecloud** [comment] 2015-10-20 22:06
@2devnull I just tested on VMware Workstation 11 and ESXi 6 and both worked fine for me.  Are you sure the SSH key is correct and you are logging in with the "rancher" user?  If ping works then networking came up.

Regarding testing on VMware, let me clarify.  We don't regularly test on ESXi.  We have yet to find an issue in which something works on Workstation/Fusion but does not work on ESXi.  For that reason we don't run an ESXi environment for testing but usually just test on Workstation/Fusion.  We have users running on VMware today w/ no issues.

**Comment by 2devnull** [comment] 2015-10-20 23:09
thanks for the clarification and for testing on ESXi 6. Can you let me see what the cloud-config file you used looks like or what a "good" clould-config file is supposed to look like. In addition, was this testing with 0.3.3?

**Comment by mbettan** [comment] 2015-10-21 06:40
My 2 cents - if your target is an Enterprise grade solution for running dockers on dev/qa/stagging/prod, you should consider ESX/Hyper-V/KVM/Cloud Publics in your testing plans. There are many differences between Fusion/Workstation and Hypervisors. If your target is only developers on their laptop, then you should also consider vagrant testing in addition to fusion/workstation.

Can you share your cloud-init file ? How did you make it working ? I understood that you solved this blocking issue with wrong cloud-init file with current beta bulds, it's not the case right?

Thanks

**Comment by ibuildthecloud** [comment] 2015-10-21 07:03
@mbettan I hope I didn't give you the impression that we only test VMware Workstation/Fusion.  Trust me we know all the complexities of hypervisors.  What we currently test is kvm, VMware fusion/workstation, esxi, Xhyve, virtual box, EC2, GCE, Azure, hyper-v, xen.  Unofficially also vultr, linode, digital ocean.  Plus various baremetal configurations.  Also small form factors devices such as minnowboard Max.

I realize now when I just tested esxi 6 just now I didn't install to disk.  I will try that tomorrow.  Maybe there is an issue with the adapter drivers.  VMware has various options for storage so I'll try them out.

Since I booted from the ISO I did not have a cloud config file.

**Comment by mbettan** [comment] 2015-10-21 07:05
Booted from the ISO was working for me on ESXi 5.5, the issue is related to install to disk

**Comment by 2devnull** [comment] 2015-10-22 16:59
@ibuildthecloud were you able to test this with installing to disk and detected the issue?

**Comment by imikushin** [comment] 2015-10-22 18:30
I've installed RancherOS v0.4.0-rc11 to disk and booted just fine on ESXi 6
hypervisor on the latest VMware Fusion Pro. I'm going to investigate this a
little more. At the very least, expect a writeup on working configuration.

One important point right now: make sure you provide enough memory to
RancherOS VM. 1024MB should work.

**Comment by sheng-liang** [comment] 2015-10-22 21:40
I have no problem getting 0.4.0-rc11 running on ESXi 6.0 Update 1. I was able to get network access.

**Comment by 2devnull** [comment] 2015-10-22 22:16
@sheng-liang - wonderful!

two things:
* can you share the config file that worked or confirm my config file a few posts earlier is correct.
* is there iso for 0.4.0-rc11 available or how can I create one

Thanks

**Comment by deniseschannon** [comment] 2015-10-22 22:34
@2devnull The iso is located on our releases page. https://github.com/rancher/os/releases/tag/v0.4.0-rc11

**Comment by mbettan** [comment] 2015-10-22 22:37
If I understand correctly, our issue is related to bad cloud config init.

What are the improvements for troubleshooting with rc11? I didn't get what changed with last release.

Do you have in the roadmap any standalone tool or pre-check to validate the cloud init file before installing to disk?

Can you share your cloud init file?

**Comment by sheng-liang** [comment] 2015-10-22 22:47
@2devnull Your cloud config file looks good to me. I modeled mine after yours:

[cloud-config.yml](https://github.com/rancher/os/files/18967/cloud-config.txt)

**Comment by 2devnull** [comment] 2015-10-22 23:03
@sheng-liang @deniseschannon - thank you for the requested info.

What I find is that if I change the type of Guest Operating System (I had 64-bit "other" OS) as my selection originally. I changed it to 64-bit then 32-bit "linux" and seem to have got further, still it got stuck at another point (see attached). I guess my question is, what is the correct Guest Operating System to use for rancherOS?

![rancher2](https://cloud.githubusercontent.com/assets/4563854/10680650/96b9b5d2-78ef-11e5-9f54-7d7194f3bcc6.png)

**Comment by sheng-liang** [comment] 2015-10-22 23:10
I select Linux and then "Other 3.x Linux (64 bit)"

I don't think this selection really matters that much though.

Are you able to boot up and login using default rancher user and get network access? You should not have to setup cloud-config.yml.

**Comment by 2devnull** [comment] 2015-10-23 03:55
0.4.0 rc11 worked. I gave it 1GB memory and 1GB disk using linux other 64-bit as the VM type. I did not try 0.3.3 again as I am hoping that 0.4 will soon be the stable one?

on another note and probably this isn't the place to ask these questions but:
* how many cores should  I give to this VM (i.e. that it will actually use)?
* what is the recommended way to create shared storage which all the instances can read/write to concurrently? I have only a single disk that has ESXi installed and now RancherOS.

Thanks for your help.

**Comment by 2devnull** [comment] 2015-10-23 04:02
BTW - will be nice to get VMWare Tools running as a system service

**Comment by sheng-liang** [comment] 2015-10-23 04:22
@2devnull Answers below:

    how many cores should I give to this VM (i.e. that it will actually use)?

It will use as many cores as you give.

    what is the recommended way to create shared storage which all the instances can read/write to concurrently? I have only a single disk that has ESXi installed and now RancherOS.

RancherOS from 4.0 will support NFS client. That's the best way to support shared storage.

**Comment by 2devnull** [comment] 2015-10-23 04:29
> RancherOS from 4.0 will support NFS client. That's the best way to support shared storage.

You mean 0.4.0, not 4.0 right? 

BTW - is there a publicly available roadmap?

**Comment by sheng-liang** [comment] 2015-10-23 04:31
@2devnull Right 0.4.0.

AFAIK, There's no roadmap beyond the list of open issues.

**Comment by 2devnull** [comment] 2015-10-23 04:34
so since I'm on 0.4.0 I should have the capability of NFS client now....correct?

Now, RancherOS will have the NFS client, so should I only allocate enough disk for RancherOS to store its Docker images and containers and setup another VM say running Debian to export the NFS shares from the disk space?
