### ISSUE TITLE
Check the validity of the console name

### ISSUE THREAD

**Issue by datawolf** [rancher/os#1073] opened 2016-06-30 11:40 UTC
**RancherOS Version: (ros os version)**

v0.5.0-rc2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

baremetal

If use want to enable or switch to `ubuntu` console and type the wrong service name `ubunut`. there is no any prompt.

It is better to Warn user when the console name is invalid.

**Comment by datawolf** [comment] 2016-06-30 12:14
https://github.com/rancher/os/pull/1074

**Comment by deniseschannon** [comment] 2016-07-05 05:47
Duplicate of #1060

**Closed by deniseschannon** 2016-07-05 05:47 UTC
