### ISSUE TITLE
open-vm-tools: crashing constantly (segfault)

### ISSUE THREAD

**Issue by giezi** [rancher/os#1096] opened 2016-07-05 16:08 UTC
Hi Rancher Team,

We have installed the newest RancherOS release v0.5.0 in a VM based on ESXi 6.0 Update1.
The open-vm-tools are crashing constantly with a the following segfault message:.

<img width="719" alt="segfault" src="https://cloud.githubusercontent.com/assets/1326203/16591144/d8a41428-42da-11e6-9f15-2e9ca1dee5bb.png">

sudo ros service ps | grep open-vm-tools
open-vm-tools           /usr/bin/vmtoolsd                              Restarting (139) 4 minutes ago

We see this symptom on multiple RancherOS instances.
Thank you in advance for your help.

Best regards
Reto

**Comment by joshwget** [comment] 2016-07-06 04:07
Pretty odd that it would just segfault right after starting. Have you experienced any instances where it didn't segfault?

Would you mind trying `vmtoolsd` in the console container? You can do this if you [switch to one of the alternate consoles](http://docs.rancher.com/os/configuration/custom-console/) and install `open-vm-tools` with the package manager of your choice. After that you should be able to start it with `vmtoolsd`.

**Comment by giezi** [comment] 2016-07-11 17:06
Hi Josh

Thank you for your quick answer!

>> Pretty odd that it would just segfault right after starting. Have you experienced any instances where it didn't segfault?
To verify the issue, i've installed several vanilla instances from scratch, the issue is on all instances (VMs) reproducible.

>> Would you mind trying vmtoolsd in the console container?

If i run the open-vm-tools in the debian console, everything is working fine (no crashes). In my view, it seems to be an issue with the open-vm-tools container image. If you like, I can provide you access to a test-system?

Best regards
Reto

**Comment by joshwget** [comment] 2016-07-25 23:44
The segfault occurs when running `vmtoolsd` in an Alpine container on Ubuntu as well. I'm not sure whether the problem is with the package or open-vm-tools itself, but we'll probably have to switch away from using Alpine until it's resolved.

Check out [this repo](https://github.com/joshwget/open-vm-tools) for a workaround image/service that can be used until the next release.

**Comment by giezi** [comment] 2016-07-27 08:54
Hi Josh,

Many thanks for your investigation!
Its not critical - therefore we wait until the issue is fixed in 0.6.0.

Best regards
Reto

**Comment by joshwget** [comment] 2016-08-30 00:18
Tested by @lucymhdavies (thanks!) and confirmed to be fixed in v0.6.0-rc5.

**Closed by joshwget** 2016-08-30 00:18 UTC
Labels: status/pr-submitted, status/to-test
