### ISSUE TITLE
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### ISSUE THREAD

**Issue by LucianoVandi** [rancher/os#1752] opened 2017-04-05 10:22 UTC
**RancherOS Version: (ros os version)**
0.9.1
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Baremetal Server

**Description**
Any command I run, `docker ps`, `docker info` or `docker version` return the message: "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

**Output of `sudo system-docker ps`**
```
97bf0dad5eef        rancher/os-console:v0.9.1   "/usr/bin/ros entrypo"   29 minutes ago      Up 29 minutes                                           console
76f22ace7064        rancher/os-docker:1.12.6    "ros user-docker"        48 minutes ago      Restarting (1) About a minute ago                       docker
1d0094f09788        rancher/os-base:v0.9.1      "/usr/bin/ros entrypo"   48 minutes ago      Up 29 minutes                                           ntp
66e0a91ddf1f        rancher/os-base:v0.9.1      "/usr/bin/ros entrypo"   48 minutes ago      Up 29 minutes                                           network
39d6d9a6dcbb        rancher/os-base:v0.9.1      "/usr/bin/ros entrypo"   48 minutes ago      Up 29 minutes                                           udev
676f50f048b3        rancher/os-base:v0.9.1      "/usr/bin/ros entrypo"   48 minutes ago      Up 29 minutes                                           syslog
7a942c670224        rancher/os-acpid:v0.9.1     "/usr/bin/ros entrypo"   48 minutes ago      Up 29 minutes                                           acpid
```

***Output of `sudo docker version` (not working without sudo...)***
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

***Output of `sudo docker info` /  `docker info`***
```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by SvenDowideit** [comment] 2017-04-06 11:01
what does `sudo system-docker logs docker` say?

**Comment by cho-cloud-cloud** [comment] 2017-05-26 02:02
Has the same issue.

When run this, it doesn't matter:

```
$ sudo ros engine switch docker-1.12.6
$ docker ps
(works well)
```

But this way not ok:

```
$ sudo ros engine enable docker-1.12.6
$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
$ sudo ros engine switch docker-1.12.6
$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by SvenDowideit** [comment] 2017-05-26 02:39
`os engine enable docker-1.12.6` doesn't actually start it - for that you either need to reboot, or use `os engine switch docker-1.12.6`

```
[rancher@test2 ~]$ docker -v
Docker version 17.03.1-ce, build c6d412e
[rancher@test2 ~]$ sudo ros engine enable docker-1.12.6
Pulling docker (rancher/os-docker:1.12.6)...
1.12.6: Pulling from rancher/os-docker
52160511971f: Pull complete 
Digest: sha256:1916540f838dbef62602e0565541a3e25dcb66649369ed697266326fc3cd615c
Status: Downloaded newer image for rancher/os-docker:1.12.6
[rancher@test2 ~]$ docker -v
Docker version 17.03.1-ce, build c6d412e
[rancher@test2 ~]$ sudo ros engine list                
disabled docker-1.10.3
disabled docker-1.11.2
enabled  docker-1.12.6
disabled docker-1.13.1
current  docker-17.03.1-ce
disabled docker-17.04.0-ce
disabled docker-17.05.0-ce
```

mind you, when I enable 1.12.6, the old docker version is still running - idk how yours is getting stopped.

**Comment by piwi91** [comment] 2017-08-02 08:18
I can reproduce this issue when using a cloud-init.conf file with the openstack image.

`> time="2017-08-02T08:14:09Z" level=info msg="Starting Docker in context: console"
> time="2017-08-02T08:14:09Z" level=info msg="Getting PID for service: console"
> time="2017-08-02T08:14:09Z" level=info msg="console PID 845"
> time="2017-08-02T08:14:10Z" level=info msg="[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=rancher-master HOME=/]"
> time="2017-08-02T08:14:10Z" level=info msg="Running [docker-runc exec -- e8f81cf10b927256e31cbba4411fe3337231ead47d6dea322dfcba6483b95f73 env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=rancher-master HOME=/ ros docker-init daemon --log-opt max-size=25m --log-opt max-file=2 --host unix:///var/run/docker.sock --storage-driver overlay --group docker --tlsverify --tlscacert=/etc/docker/tls/ca.pem --tlscert=/etc/docker/tls/server-cert.pem --tlskey=/etc/docker/tls/server-key.pem -H=0.0.0.0:2376]"
[root@rancher-master rancher]# cat /var/log/docker.log
Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
Could not load X509 key pair (cert: "/etc/docker/tls/server-cert.pem", key: "/etc/docker/tls/server-key.pem"): open /etc/docker/tls/server-cert.pem: no such file or directory
`

**Comment by SvenDowideit** [comment] 2017-08-02 09:02
@piwi91 that's in the cloud-init.conf?

**Comment by SvenDowideit** [comment] 2017-08-02 09:04
I would suggest that the user docker daemon is exiting due to 

`Could not load X509 key pair (cert: "/etc/docker/tls/server-cert.pem", key: "/etc/docker/tls/server-key.pem"): open /etc/docker/tls/server-cert.pem: no such file or directory`

you'll need to fix that....

**Comment by piwi91** [comment] 2017-08-02 09:54
@SvenDowideit Yes, I had the TLS functionality enabled without the certificates (oops...). So, by removing the TLS (or by adding the certificates) it works as expected!

**Comment by SvenDowideit** [comment] 2017-08-03 23:50
excellent :) closing

**Closed by SvenDowideit** 2017-08-03 23:50 UTC
Labels: kind/question
