### ISSUE TITLE
docker-machine create happend errors in version 1.0.3

### ISSUE THREAD

**Issue by JermineHu** [rancher/os#1961] opened 2017-07-03 08:07 UTC
**RancherOS Version: (V1.0.3)**

To excute `docker-machine create -d virtualbox --virtualbox-boot2docker-url rancheros.iso $DM_VM_NAME`  get some errors.  screenshot detail was in below. Thx. 

![qq20170703-160216](https://user-images.githubusercontent.com/18027793/27783624-7e9dfa32-6009-11e7-9ed6-ea182dc82f79.png)

**Comment by superseb** [comment] 2017-07-03 08:18
Thanks for reporting, closing as duplicate of https://github.com/rancher/os/issues/1956

**Closed by superseb** 2017-07-03 08:18 UTC
