### ISSUE TITLE
open-vm-tools won't shutdown or restart the VM again

### ISSUE THREAD

**Issue by benok** [rancher/os#2121] opened 2017-09-24 18:01 UTC
Hi,
I'm using rancher os v1.1.0 on ESXi 6.0 3620759.

open-vm-tools seems not to work again. 
Please see the output of `sudo system-docker logs -f open-vm-tools` below.
```
rancher@sd-rancher1:~$ sudo system-docker logs -f open-vm-tools
Incorrect Usage.

NAME:
   /sbin/shutdown - /sbin/shutdown RancherOS
built: '2017-08-29T23:43:58Z'

USAGE:
   shutdown [global options] [arguments...]

VERSION:
   v1.1.0

AUTHOR(S):
   Rancher Labs, Inc.

GLOBAL OPTIONS:
   -f, --force     Force immediate halt, power-off, reboot. Do not contact the init system.
   -H, --halt      halt the machine
   -P, --poweroff  halt the machine
   -r, --reboot    reboot after shutdown
   --version, -v   print the version

```
(moved from https://github.com/rancher/os/issues/1543#issuecomment-330764000)

**Comment by ikappas** [comment] 2017-10-14 16:06
I am experiencing the same issue with rancher os v1.1.0 on ESXi 6.5.0 Update 1 (Build 5969303)

**Comment by vancluever** [comment] 2017-10-20 17:08
Doing some investigation on this as I want use rancher for some "bare metal" work I'm doing for the Terraform vSphere provider... and it's working amazing so far... I'm super excited, but we will need guest shutdown capabilities!

I found this in the open-vm-tools shutdown logic: https://github.com/vmware/open-vm-tools/blob/e0a7b4e98bd6d6af06d31212dfdc82610d37e4d3/open-vm-tools/lib/system/systemLinux.c#L376

But:

```
[root@rancher ~]# system-docker exec -it open-vm-tools /bin/bash        
root@rancher:/# /sbin/shutdown -h now
Incorrect Usage.

NAME:
   /sbin/shutdown - /sbin/shutdown RancherOS
built: '2017-08-29T23:43:58Z'

USAGE:
   shutdown [global options] [arguments...]
   
VERSION:
   v1.1.0
   
AUTHOR(S):
   Rancher Labs, Inc. 
   
GLOBAL OPTIONS:
   -f, --force     Force immediate halt, power-off, reboot. Do not contact the init system.
   -H, --halt      halt the machine
   -P, --poweroff  halt the machine
   -r, --reboot    reboot after shutdown
   --version, -v   print the version
```
Running an `strace` on `vmtoolsd`, it does for sure look like this is the command that rancher is executing, and the output that it's getting back. Assuming this is the busybox shutdown, and this vmtoolsd is more than likely not built against that, is this a regression related to bind mounts  again?

Also, the reboot command seems to go thru, but fails:

```
1416  write(1, "[            ] shutdown:fatal: Error response from daemon: Invalid container name (/sbin/shutdown), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed\n", 143 <unfinished ...>
```

**Comment by vancluever** [comment] 2017-10-20 17:19
I'd imagine this will be a two-part fix in `cmd/power`: 

* Accept `-h` (lowercase) as a valid halt flag - is there a reason why it was chosen as uppercase (maybe this is busybox-like)?
* Fix `reboot()` to launch a container with a proper name (from the logs here, looks like it's trying to launch as `/sbin/shutdown`)

**Comment by vancluever** [comment] 2017-10-20 17:23
PS: This does the same thing in the console container:

```
[root@rancher ~]# /sbin/shutdown -H now 
[            ] shutdown:info: Setting /sbin/shutdown timeout to 60 (rancher.shutdown_timeout set to 60)
.[            ] shutdown:fatal: Error response from daemon: Invalid container name (/sbin/shutdown), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
[root@rancher ~]# /sbin/shutdown -r now
[            ] shutdown:info: Setting /sbin/shutdown timeout to 60 (rancher.shutdown_timeout set to 60)
.[            ] shutdown:fatal: Error response from daemon: Invalid container name (/sbin/shutdown), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

```

**Comment by vancluever** [comment] 2017-10-20 20:18
Update: I've added the appropriate stuff to the `cmd/power` package (turns out that `shutdown` wasn't checking to see if it was called via an absolute path or not, which is why the bad container name was being passed) and am just uploading my artifacts to see if this fixes it for vSphere. If it does I'll be putting in a PR when I'm done!

**Comment by vancluever** [comment] 2017-10-21 00:37
PR is in! I've tested against our own ESXi 6.5 lab here over iPXE and sending guest shutdown and reboot commands now work like they say they do on the tin.

If anyone wants to give this a shot, note all you need is to build the updated rootfs and deploy accordingly. No update to any containers is necessary for this fix to work. :tada:

**Comment by benok** [comment] 2017-10-31 09:28
@vancluever Thank you for fixing the issue.
I don't have build env for rancher-os now, and it seems very slow for them to fix this. 
Could you upload fixed power/shutdown to somewhere ?

**Comment by vancluever** [comment] 2017-11-08 16:35
Hey @benok - sorry I haven't responded to this. If I have the time to upload it I will do so to the releases page on my fork, but the easiest way to probably do this would be to get the build environment set up. The instructions here can help: http://rancher.com/docs/os/v1.1/en/contributing/ and if it's at all possible to get your hands on a Linux environment of reasonable power you should be able to build the initrd using the directions and running the `make dev` command.

Hope that helps!

**Comment by lucymhdavies** [comment] 2017-11-21 15:10
We see the same issue, in ESXi 6.0.

We can work around it, but would be good to have a fix.
If I have time, I'll get a build env setup and try that myself too.

**Comment by lucymhdavies** [comment] 2017-11-22 12:12
As my workaround, I've followed instructions from here to get a custom shutdown command:
https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vmtools.install.doc%2FGUID-35F34AE7-78E0-4BCF-B7C4-EFC29DE18824.html

It's a dirty dirty hack, but it works for now until that PR is reviewed and merged.

**Closed** 2018-01-23 10:07 UTC
