### ISSUE TITLE
Cannot install RancherOS - /dev/sr0

### ISSUE THREAD

**Issue by Angelinsky7** [rancher/os#2241] opened 2018-01-30 17:49 UTC
Version : rancher/os:v1.2.0-rc2
Installation : baremetal

I downloaded the latest image, created an usb bootable disk with rufus (from window 10 with default options) and tried to install...

```
[rancher@rancher ~]$ sudo ros install -c cloud-config.yml -d /dev/nvme0
INFO[0000] No install type specified...defaulting to generic
Installing from rancher/os:v1.2.0-rc2
Continue [y/N]: y
INFO[0000] start !isoinstallerloaded
ERRO[0000] Failed to get boot iso: stat /dev/sr0: no such file or directory
There is no boot iso drive, terminate the task
FATA[0000] Failed to run install                         err="stat /dev/sr0: no such file or directory"
```

```
coud-config
hostname: dost

rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 10.138.222.201/24
        gateway: 10.138.222.1
      dns:
        nameservers:
          - 10.138.222.1

ssh_authorized_keys:
  - ssh-rsa (A KEY) (A NAME)
```

```
[rancher@rancher ~]$ blkid
/dev/sda1: LABEL="RANCHEROS" UUID="72E6-FBFF" TYPE="vfat" PARTUUID="012850b0-01"
```

The label is always in capital letter, i tried to change it but everytime in captial... (i know that is should be "RancherOS")
What can i do ?
Thanks for your help and os !!!

**Comment by niusmallnan** [comment] 2018-02-10 03:35
I don't have a windows, not sure whether caused by rufus.
Later I will try to reproduce it.

**Comment by Shifter2600** [comment] 2018-02-12 22:26
I am having the same issue.
Would this be related to setting up another computer with the same USB as the initial one. This is my 2nd install. The 1st one went fine. Is there anything changed on the USB after the initial that would cause the 2nd to fail?

**Comment by Shifter2600** [comment] 2018-02-13 03:33
A little more on the issue. On the 1st machine I do have a cd/dvd drive so there is a /dev/sr0 mounted.
But on my other machines there is not. And it'sa these other machines that I am getting these errors.

**Comment by Shifter2600** [comment] 2018-02-13 03:42
So :s I guess if you don't have a /dev/sr0 just sudo mkdir /dev/sr0 and problem solved.

**Comment by SamMousa** [comment] 2018-02-14 12:26
> So :s I guess if you don't have a /dev/sr0 just sudo mkdir /dev/sr0 and problem solved.

I can confirm that this workaround works!

**Comment by eyespies** [comment] 2018-02-14 16:00
I just experienced this exact issue when trying to install Rancher OS as a KVM guest under entperise Linux. The suggested work around also allowed me to move past this issue. Just wanted to note that this is not limited to Rancher OS on Windows hosts.

**Comment by niusmallnan** [comment] 2018-03-15 02:30
I don't have a test setup, will be cool if anybody can help me to verify this issue.
Just to use [rancheros v1.3.0-rc1](https://github.com/rancher/os/releases/download/v1.3.0-rc1/rancheros.iso)

**Comment by kingsd041** [comment] 2018-03-20 03:53
Fixed in rancheros-v1.3.0-rc1, below is my test record
```
[root@rancher ~]# blkid
/dev/sdb1: LABEL="RANCHEROS" UUID="D45A-7A19" TYPE="vfat" PARTUUID="0016d2b9-01"

[root@rancher ~]# ros -v
version v1.3.0-rc1 from os image rancher/os:v1.3.0-rc1

[root@rancher ~]# fdisk -l
Disk /dev/sda: 30 GiB, 32212254720 bytes, 62914560 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

[root@rancher conf]# ls /dev/sr0
ls: /dev/sr0: No such file or directory
```
```
[root@rancher conf]# ros install -c cloud-config1.yml -d /dev/sda
INFO[0000] No install type specified...defaulting to generic
Installing from rancher/os:v1.3.0-rc1
Continue [y/N]: y
INFO[0020] start !isoinstallerloaded
INFO[0022] trying to load /bootiso/rancheros/installer.tar.gz
cd7100a72410: Loading layer [==================================================>]  4.403MB/4.403MB
7592fde68a53: Loading layer [==================================================>]   15.6MB/15.6MB
f86f141aaa51: Loading layer [==================================================>]   5.12kB/5.12kB
1b5443c63fdd: Loading layer [==================================================>]  18.94MB/18.94MB
777ad398bea7: Loading layer [==================================================>]  1.645MB/1.645MB
62cbd856f168: Loading layer [==================================================>]  1.536kB/1.536kB
6b1c41c97e51: Loading layer [==================================================>]   2.56kB/2.56kB
90fc9c90888b: Loading layer [==================================================>]  3.072kB/3.072kB
Loaded image: rancher/os-installer:latest
INFO[0024] Loaded images from /bootiso/rancheros/installer.tar.gz
INFO[0024] starting installer container for rancher/os-installer:latest (new)
Installing from rancher/os-installer:latest
mke2fs 1.43.7 (16-Oct-2017)
Creating filesystem with 7863808 4k blocks and 7864320 inodes
Filesystem UUID: 1db5b273-a5d5-48c1-9b91-2b728b86187a
Superblock backups stored on blocks:
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
	4096000

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done

Continue with reboot [y/N]: y
INFO[0048] Rebooting
INFO[0048] Setting reboot timeout to 60 (rancher.shutdown_timeout set to 60)
...^[            ] reboot:info: Setting reboot timeout to 60 (rancher.shutdown_timeout set to 60)
.=.[            ] reboot:info: Stopping /docker : c423fb2a9737
...........C..........[            ] reboot:info: Stopping /ntp : ea3f08e9f2c8
>.[            ] reboot:info: Stopping /network : 4800f4efc3be
:[            ] reboot:info: Stopping /udev : 879c3230586e
A[            ] reboot:info: Stopping /system-cron : ed7b79bfeca9
;[            ] reboot:info: Stopping /acpid : 34a244e36ec4
.=.[            ] reboot:info: Stopping /syslog : dd67c93f0dcd
G[            ] reboot:info: Console Stopping [/console] : 0deed3470bc8
Connection to 192.168.2.221 closed by remote host.
Connection to 192.168.2.221 closed.
```

**Closed by kingsd041** 2018-03-20 03:53 UTC
Labels: area/ros, kind/enhancement, status/to-test

**Comment by Sebisnow** [comment] 2019-01-03 15:22
Happens again with v1.5.0:
```bash
[rancher@rancher ~]$ sudo ros install -c cloud-config.yml -d /dev/sda -t gptsyslinux
Installing from rancher/os:v1.5.0
Continue [y/N]: y
INFO[0004] start !isoinstallerloaded                    
ERRO[0004] Failed to get boot iso: stat /dev/sr0: no such file or directory 
There is no boot iso drive, terminate the task
FATA[0004] Failed to run install                         err="stat /dev/sr0: no such file or directory"
```

**Comment by niusmallnan** [comment] 2019-01-04 00:09
@Sebisnow Did you check the label? Can you provide more info so that I can replay?

**Comment by niusmallnan** [comment] 2019-01-04 07:31
@Sebisnow This has nothing to do with this issue, I create a new one.

**Comment by kidhasmoxy** [comment] 2019-05-23 16:38
I'm running into this issue and I think it's related but I want to make sure. 

I'm PXE booting into Rancher 1.5.1 using netboot.xyz. The installation works fine on a virtual machine with an empty virtual CD drive attached. Unfortunately, I run into the /dev/sr0 issue on baremetal devices, as none of my devices have a CD drive. 

The installation continues if I use the following workaround, but the cloud-config does not apply. 

Workaround 

1. sudo mkdir /dev/sr0
1. use explicit flags for nvme drive -d /dev/nvme0n1 and -p /dev/nvme0n1p1

The problem is on boot, none of the expected services are pulled and started. I don't even have user docker running as the cloud config changes the engine version. ROS shows everything as enabled and selected, but I have to rerun the commands manually to get the pull and startup process to happen.

**Comment by niusmallnan** [comment] 2019-05-24 01:45
@kidhasmoxy Please file another issue, this issue is about the usb booting.
It is better that you can provide the `ros install --debug -d xxxxx` command and cloud-config.yml.
