### ISSUE TITLE
Stuck wenn try to reboot (v0.4.0-rc5)

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#563] opened 2015-09-12 09:44 UTC
RancherOS v0.4.0-rc5

Tried to reboot RancherOS without success:

    sudo reboot

ssh session closed. Ping OK, Impossible to connect via ssh also after minitues. Reboot isn't done. Stucks during shutdown?

Boots up without problems after power off the machine and start it again.

**Comment by ibuildthecloud** [comment] 2015-09-12 12:28
Yes, this is the major blocker to us releasing v0.4, it is due to a bug in Docker itself.  
https://github.com/docker/docker/issues/16206

**Comment by deniseschannon** [comment] 2015-09-12 14:01
Duplicate of #545.

**Closed by deniseschannon** 2015-09-12 14:01 UTC

**Comment by pwFoo** [comment] 2015-09-12 14:36
Thanks, I'll follow #545.
