### ISSUE TITLE
ros engine switch multiple times.. user docker fails.

### ISSUE THREAD

**Issue by skyscooby** [rancher/os#1500] opened 2017-01-09 01:28 UTC
**RancherOS Version: (ros os version)**
v0.8.0-rc2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Virtualbox.. booting ISO image.

-> Run ros engine switch docker-1.10.3
-> run docker info.. (reports version 1.10.3)
-> run ros engine switch docker-1.12.3 (to revert change back to default).
-> run docker info.. (user docker will be down and unable to start..).

Quick inspection of logs seems to indicate an issue with docker bridge already being configured.. but user docker is not able to start again. Also tried the above with 1.11.2 and same behaviour.. after first switch of the engine subsequent switches fail.

**Comment by SvenDowideit** [comment] 2017-01-09 01:31
@deniseschannon I recal you guys mentioning a problem like this existing for quite a while?

**Comment by joshwget** [comment] 2017-01-09 01:39
This does seem familiar and from what I remember it was an upstream bug. Can you share the logs @skyscooby?

`system-docker logs docker`
`cat /var/log/docker.log`

**Comment by skyscooby** [comment] 2017-01-09 03:29
system docker is running this command over and over. (from system-docker logs docker)
time="2017-01-09T03:25:31Z" level=info msg="Running [docker-runc exec -- a573d008f0cd1167acf6697f76395929d385d109c18b15739bad2d7830100a71 env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=rancher HOME=/ ros docker-init daemon --group docker --host unix:///var/run/docker.sock --storage-driver overlay --log-opt max-file=2 --log-opt max-size=25m]"

/var/log/docker.log shows these errors:
time="2017-01-09T03:25:05.731277807Z" level=info msg="previous instance of containerd still alive (1067)" 
time="2017-01-09T03:25:05.737398584Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2017-01-09T03:25:05.770687397Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address" 
time="2017-01-09T03:25:05.771461016Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: cannot create network 4967f56fa01ecf8247437a620bafdaed7b1f339d1795053a4e68987da14a5a87 (docker0): conflicts with network 14e2dac8d814a597723a95777fb6fd11b6a2f6fd6e97670b20cb82b96239c8d4 (docker0): networks have same bridge name" 
time="2017-01-09T03:25:31.870947520Z" level=info msg="previous instance of containerd still alive (1067)" 
time="2017-01-09T03:25:31.875640723Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2017-01-09T03:25:31.913383248Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address" 
time="2017-01-09T03:25:31.914809982Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: cannot create network 3c2c256e606cb30fee6cf1ee175a3c6cbda61923cb7401932dd52989a5e8bba6 (docker0): conflicts with network 14e2dac8d814a597723a95777fb6fd11b6a2f6fd6e97670b20cb82b96239c8d4 (docker0): networks have same bridge name" 

There is still a containerd process running..

**Comment by deniseschannon** [comment] 2017-01-09 04:06
Yep, this is a duplicate of: https://github.com/rancher/os/issues/1227

**Closed by deniseschannon** 2017-01-09 04:06 UTC
