### ISSUE TITLE
network not ready

### ISSUE THREAD

**Issue by strowi** [rancher/os#2199] opened 2017-12-29 20:46 UTC
**RancherOS Version: v1.1.2**

**Where are you running RancherOS? baremetal**

Hi,

im running a pxe-environment of 5 baremetal servers. 3 boot and work flawless. 
Only 2 seem to have some networking trouble on bootup and fail to download the cloud-config. But they are reachably by ssh, only i cannot login because no key/pass is present.

Maybe some timeout occuring? 

```
~> cat cloud-init-save.log 
time="2017-12-29T20:28:20Z" level=debug msg="START: [cloud-init-save] in /" 
time="2017-12-29T20:28:20Z" level=info msg="Running cloud-init-save" 
time="2017-12-29T20:28:20Z" level=info msg=SaveCloudConfig 
time="2017-12-29T20:28:20Z" level=debug msg="init: SaveCloudConfig(pre ApplyNetworkConfig): netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string(nil), Search:[]string(nil)}, Interfaces:map[string]netconf.InterfaceConfig(nil), PostCmds:[]string(nil), HTTPProxy:"", HTTPSProxy:"", NoProxy:""}" 
time="2017-12-29T20:28:20Z" level=info msg="Apply Network Config" 
time="2017-12-29T20:28:20Z" level=debug msg="Config: &netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string(nil), Search:[]string(nil)}, Interfaces:map[string]netconf.InterfaceConfig{"eth*":netconf.InterfaceConfig{Match:"", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}, "lo":netconf.InterfaceConfig{Match:"", DHCP:false, DHCPArgs:"", Address:"", Addresses:[]string{"127.0.0.1/8", "::1/128"}, IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}}, PostCmds:[]string(nil), HTTPProxy:"", HTTPSProxy:"", NoProxy:""}" 
time="2017-12-29T20:28:20Z" level=debug msg="runCmds(on ): []" 
time="2017-12-29T20:28:20Z" level=debug msg="applyOuter(%!V(bool=false), false)" 
time="2017-12-29T20:28:20Z" level=debug msg="Config(lo): netconf.InterfaceConfig{Match:"lo", DHCP:false, DHCPArgs:"", Address:"", Addresses:[]string{"127.0.0.1/8", "::1/128"}, IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}" 
time="2017-12-29T20:28:20Z" level=debug msg="runCmds(on lo): []" 
time="2017-12-29T20:28:20Z" level=info msg="Applying 127.0.0.1/8 to lo" 
time="2017-12-29T20:28:20Z" level=info msg="Applying ::1/128 to lo" 
time="2017-12-29T20:28:20Z" level=debug msg="runCmds(on lo): []" 
time="2017-12-29T20:28:20Z" level=debug msg="applyOuter(%!V(bool=false), false)" 
time="2017-12-29T20:28:20Z" level=debug msg="Config(eth0): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}" 
time="2017-12-29T20:28:20Z" level=debug msg="runCmds(on eth0): []" 
time="2017-12-29T20:28:20Z" level=debug msg="runCmds(on eth0): []" 
time="2017-12-29T20:28:20Z" level=debug msg="applyOuter(%!V(bool=false), false)" 
time="2017-12-29T20:28:20Z" level=debug msg="Config(eth1): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}" 
time="2017-12-29T20:28:20Z" level=debug msg="runCmds(on eth1): []" 
time="2017-12-29T20:28:20Z" level=debug msg="runCmds(on eth1): []" 
time="2017-12-29T20:28:20Z" level=info msg="Running DHCP on eth1: dhcpcd -MA4 -e force_hostname=true -w --debug eth1" 
time="2017-12-29T20:28:20Z" level=info msg="Running DHCP on eth0: dhcpcd -MA4 -e force_hostname=true -w --debug eth0" 
time="2017-12-29T20:28:50Z" level=info msg="Checking to see if DNS was set by DHCP" 
time="2017-12-29T20:28:50Z" level=info msg="dns testing lo" 
time="2017-12-29T20:28:50Z" level=error msg="exit status 1" 
time="2017-12-29T20:28:50Z" level=debug msg="getDhcpLease lo: " 
time="2017-12-29T20:28:50Z" level=debug msg="line: []" 
time="2017-12-29T20:28:50Z" level=info msg="dns testing eth0" 
time="2017-12-29T20:28:50Z" level=error msg="exit status 1" 
time="2017-12-29T20:28:50Z" level=debug msg="getDhcpLease eth0: " 
time="2017-12-29T20:28:50Z" level=debug msg="line: []" 
time="2017-12-29T20:28:50Z" level=info msg="dns testing eth1" 
time="2017-12-29T20:28:50Z" level=error msg="exit status 1" 
time="2017-12-29T20:28:50Z" level=debug msg="getDhcpLease eth1: " 
time="2017-12-29T20:28:50Z" level=debug msg="line: []" 
time="2017-12-29T20:28:50Z" level=debug msg="runCmds(on ): []" 
time="2017-12-29T20:28:50Z" level=info msg="Writing default resolv.conf - no user setting, and no DHCP setting" 
time="2017-12-29T20:28:50Z" level=debug msg="Resolve.conf == [nameserver 8.8.8.8
nameserver 8.8.4.4
], %!s(<nil>)" 
time="2017-12-29T20:28:50Z" level=info msg="Apply Network Config SyncHostname" 
time="2017-12-29T20:28:50Z" level=info msg="datasources that will be consided: []string{"url:http://10.10.0.10:8080/assets/rancher/rancher.yml"}" 
time="2017-12-29T20:28:50Z" level=info msg="cloud-init: Checking availability of "url"" 
time="2017-12-29T20:28:50Z" level=info msg="cloud-init: Datasource unavailable, skipping: url: http://10.10.0.10:8080/assets/rancher/rancher.yml (lastError: Unable to fetch data: Get http://10.10.0.10:8080/assets/rancher/rancher.yml: dial tcp 10.10.0.10:8080: connect: network is unreachable)" 
time="2017-12-29T20:28:50Z" level=info msg="Cloud-init datasource that was used: %!s(<nil>)" 
time="2017-12-29T20:28:51Z" level=debug msg="init: SaveCloudConfig(post ApplyNetworkConfig): netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string(nil), Search:[]string(nil)}, Interfaces:map[string]netconf.InterfaceConfig(nil), PostCmds:[]string(nil), HTTPProxy:"", HTTPSProxy:"", NoProxy:""}" 
time="2017-12-29T20:28:51Z" level=info msg="Apply Network Config" 
time="2017-12-29T20:28:51Z" level=debug msg="Config: &netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string(nil), Search:[]string(nil)}, Interfaces:map[string]netconf.InterfaceConfig{"eth*":netconf.InterfaceConfig{Match:"", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}, "lo":netconf.InterfaceConfig{Match:"", DHCP:false, DHCPArgs:"", Address:"", Addresses:[]string{"127.0.0.1/8", "::1/128"}, IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}}, PostCmds:[]string(nil), HTTPProxy:"", HTTPSProxy:"", NoProxy:""}" 
time="2017-12-29T20:28:51Z" level=debug msg="runCmds(on ): []" 
time="2017-12-29T20:28:51Z" level=debug msg="applyOuter(%!V(bool=false), false)" 
time="2017-12-29T20:28:51Z" level=debug msg="Config(lo): netconf.InterfaceConfig{Match:"lo", DHCP:false, DHCPArgs:"", Address:"", Addresses:[]string{"127.0.0.1/8", "::1/128"}, IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}" 
time="2017-12-29T20:28:51Z" level=debug msg="runCmds(on lo): []" 
time="2017-12-29T20:28:51Z" level=info msg="Applying 127.0.0.1/8 to lo" 
time="2017-12-29T20:28:51Z" level=info msg="Applying ::1/128 to lo" 
time="2017-12-29T20:28:51Z" level=debug msg="runCmds(on lo): []" 
time="2017-12-29T20:28:51Z" level=debug msg="applyOuter(%!V(bool=false), false)" 
time="2017-12-29T20:28:51Z" level=debug msg="Config(eth0): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}" 
time="2017-12-29T20:28:51Z" level=debug msg="runCmds(on eth0): []" 
time="2017-12-29T20:28:51Z" level=debug msg="runCmds(on eth0): []" 
time="2017-12-29T20:28:51Z" level=debug msg="applyOuter(%!V(bool=false), false)" 
time="2017-12-29T20:28:51Z" level=debug msg="Config(eth1): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}" 
time="2017-12-29T20:28:51Z" level=debug msg="runCmds(on eth1): []" 
time="2017-12-29T20:28:51Z" level=debug msg="runCmds(on eth1): []" 
time="2017-12-29T20:28:51Z" level=info msg="Running DHCP on eth1: dhcpcd -MA4 -e force_hostname=true -w --debug eth1" 
time="2017-12-29T20:28:51Z" level=info msg="Running DHCP on eth0: dhcpcd -MA4 -e force_hostname=true -w --debug eth0" 
time="2017-12-29T20:28:51Z" level=info msg="Checking to see if DNS was set by DHCP" 
time="2017-12-29T20:28:51Z" level=info msg="dns testing lo" 
time="2017-12-29T20:28:51Z" level=error msg="exit status 1" 
time="2017-12-29T20:28:51Z" level=debug msg="getDhcpLease lo: " 
time="2017-12-29T20:28:51Z" level=debug msg="line: []" 
time="2017-12-29T20:28:51Z" level=info msg="dns testing eth0" 
time="2017-12-29T20:28:51Z" level=error msg="exit status 1" 
time="2017-12-29T20:28:51Z" level=debug msg="getDhcpLease eth0: " 
time="2017-12-29T20:28:51Z" level=debug msg="line: []" 
time="2017-12-29T20:28:51Z" level=info msg="dns testing eth1" 
time="2017-12-29T20:28:51Z" level=error msg="exit status 1" 
time="2017-12-29T20:28:51Z" level=debug msg="getDhcpLease eth1: " 
time="2017-12-29T20:28:51Z" level=debug msg="line: []" 
time="2017-12-29T20:28:51Z" level=debug msg="runCmds(on ): []" 
time="2017-12-29T20:28:51Z" level=info msg="Writing default resolv.conf - no user setting, and no DHCP setting" 
time="2017-12-29T20:28:51Z" level=debug msg="Resolve.conf == [nameserver 8.8.8.8
nameserver 8.8.4.4
], %!s(<nil>)" 
time="2017-12-29T20:28:51Z" level=info msg="Apply Network Config SyncHostname"
```

**Comment by niusmallnan** [comment] 2018-01-02 01:37
After DCHP is done, does the network have access to `http://10.10.0.10:8080/assets/rancher/rancher.yml`?

I see eth0 and eth1 will use DHCP, in your network whether the routing table is affected, I mean, affect the visit to `http://10.10.0.10:8080`.

**Comment by strowi** [comment] 2018-01-02 09:49
After some more searching... it seems it's a issue on our site where the server has a connection and looses it for ~10-20sec. before it being stable..
sorry for the fuss..

**Comment by strowi** [comment] 2018-01-16 12:55
sorry to say.. this doesn't seem to be the root cause... 
the connection drop i mentioned, is the switch from pxe boot to system dhcp...

**Comment by lanchongyizu** [comment] 2018-01-22 02:59
**RancherOS Version: v1.1.3**

**Where are you running RancherOS? baremetal**

We encounter the same issue. BTW, when will the release v1.2.0 be ready?

```
[rancher@rancher boot]$ cat cloud-init-save.log
time="2018-01-21T13:02:44Z" level=debug msg="START: [cloud-init-save] in /"
time="2018-01-21T13:02:44Z" level=info msg="Running cloud-init-save"
time="2018-01-21T13:02:45Z" level=info msg=SaveCloudConfig
time="2018-01-21T13:02:45Z" level=debug msg="init: SaveCloudConfig(pre ApplyNetworkConfig): netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string(nil), Search:[]string(nil)}, Interfaces:map[string]netconf.InterfaceConfig(nil), PostCmds:[]string(nil), HTTPProxy:"", HTTPSProxy:"", NoProxy:""}"
time="2018-01-21T13:02:45Z" level=info msg="Apply Network Config"
time="2018-01-21T13:02:45Z" level=debug msg="Config: &netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string(nil), Search:[]string(nil)}, Interfaces:map[string]netconf.InterfaceConfig{"eth*":netconf.InterfaceConfig{Match:"", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}, "lo":netconf.InterfaceConfig{Match:"", DHCP:false, DHCPArgs:"", Address:"", Addresses:[]string{"127.0.0.1/8", "::1/128"}, IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}}, PostCmds:[]string(nil), HTTPProxy:"", HTTPSProxy:"", NoProxy:""}"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on ): []"
time="2018-01-21T13:02:45Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:02:45Z" level=debug msg="Config(lo): netconf.InterfaceConfig{Match:"lo", DHCP:false, DHCPArgs:"", Address:"", Addresses:[]string{"127.0.0.1/8", "::1/128"}, IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on lo): []"
time="2018-01-21T13:02:45Z" level=info msg="Applying 127.0.0.1/8 to lo"
time="2018-01-21T13:02:45Z" level=info msg="Applying ::1/128 to lo"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on lo): []"
time="2018-01-21T13:02:45Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:02:45Z" level=debug msg="Config(eth0): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on eth0): []"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on eth0): []"
time="2018-01-21T13:02:45Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:02:45Z" level=debug msg="Config(eth1): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on eth1): []"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on eth1): []"
time="2018-01-21T13:02:45Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:02:45Z" level=debug msg="Config(eth2): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on eth2): []"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on eth2): []"
time="2018-01-21T13:02:45Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:02:45Z" level=debug msg="Config(eth3): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on eth3): []"
time="2018-01-21T13:02:45Z" level=debug msg="runCmds(on eth3): []"
time="2018-01-21T13:02:45Z" level=info msg="Running DHCP on eth0: dhcpcd -MA4 -e force_hostname=true -w --debug eth0"
time="2018-01-21T13:02:45Z" level=info msg="Running DHCP on eth1: dhcpcd -MA4 -e force_hostname=true -w --debug eth1"
time="2018-01-21T13:02:45Z" level=info msg="Running DHCP on eth3: dhcpcd -MA4 -e force_hostname=true -w --debug eth3"
time="2018-01-21T13:02:45Z" level=info msg="Running DHCP on eth2: dhcpcd -MA4 -e force_hostname=true -w --debug eth2"
time="2018-01-21T13:03:16Z" level=info msg="Checking to see if DNS was set by DHCP"
time="2018-01-21T13:03:16Z" level=info msg="dns testing lo"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease lo: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=info msg="dns testing eth0"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease eth0: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=info msg="dns testing eth1"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease eth1: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=info msg="dns testing eth2"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease eth2: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=info msg="dns testing eth3"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease eth3: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on ): []"
time="2018-01-21T13:03:16Z" level=info msg="Writing default resolv.conf - no user setting, and no DHCP setting"
time="2018-01-21T13:03:16Z" level=debug msg="Resolve.conf == [nameserver 8.8.8.8
nameserver 8.8.4.4
], %!s(<nil>)"
time="2018-01-21T13:03:16Z" level=info msg="Apply Network Config SyncHostname"
time="2018-01-21T13:03:16Z" level=info msg="datasources that will be consided: []string{"url:http://172.31.128.1:9080/api/current/templates/cloud-config.yaml?nodeId=5a5b2e9a80e3977d186a543b"}"
time="2018-01-21T13:03:16Z" level=info msg="cloud-init: Checking availability of "url""
time="2018-01-21T13:03:16Z" level=info msg="cloud-init: Datasource unavailable, skipping: url: http://172.31.128.1:9080/api/current/templates/cloud-config.yaml?nodeId=5a5b2e9a80e3977d186a543b (lastError: Unable to fetch data: Get http://172.31.128.1:9080/api/current/templates/cloud-config.yaml?nodeId=5a5b2e9a80e3977d186a543b: dial tcp 172.31.128.1:9080: connect: network is unreachable)"
time="2018-01-21T13:03:16Z" level=info msg="Cloud-init datasource that was used: %!s(<nil>)"
time="2018-01-21T13:03:16Z" level=debug msg="init: SaveCloudConfig(post ApplyNetworkConfig): netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string(nil), Search:[]string(nil)}, Interfaces:map[string]netconf.InterfaceConfig(nil), PostCmds:[]string(nil), HTTPProxy:"", HTTPSProxy:"", NoProxy:""}"
time="2018-01-21T13:03:16Z" level=info msg="Apply Network Config"
time="2018-01-21T13:03:16Z" level=debug msg="Config: &netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string(nil), Search:[]string(nil)}, Interfaces:map[string]netconf.InterfaceConfig{"eth*":netconf.InterfaceConfig{Match:"", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}, "lo":netconf.InterfaceConfig{Match:"", DHCP:false, DHCPArgs:"", Address:"", Addresses:[]string{"127.0.0.1/8", "::1/128"}, IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}}, PostCmds:[]string(nil), HTTPProxy:"", HTTPSProxy:"", NoProxy:""}"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on ): []"
time="2018-01-21T13:03:16Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:03:16Z" level=debug msg="Config(lo): netconf.InterfaceConfig{Match:"lo", DHCP:false, DHCPArgs:"", Address:"", Addresses:[]string{"127.0.0.1/8", "::1/128"}, IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on lo): []"
time="2018-01-21T13:03:16Z" level=info msg="Applying 127.0.0.1/8 to lo"
time="2018-01-21T13:03:16Z" level=info msg="Applying ::1/128 to lo"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on lo): []"
time="2018-01-21T13:03:16Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:03:16Z" level=debug msg="Config(eth0): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on eth0): []"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on eth0): []"
time="2018-01-21T13:03:16Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:03:16Z" level=debug msg="Config(eth1): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on eth1): []"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on eth1): []"
time="2018-01-21T13:03:16Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:03:16Z" level=debug msg="Config(eth2): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on eth2): []"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on eth2): []"
time="2018-01-21T13:03:16Z" level=debug msg="applyOuter(%!V(bool=false), false)"
time="2018-01-21T13:03:16Z" level=debug msg="Config(eth3): netconf.InterfaceConfig{Match:"eth*", DHCP:true, DHCPArgs:"", Address:"", Addresses:[]string(nil), IPV4LL:false, Gateway:"", GatewayIpv6:"", MTU:0, Bridge:"", Bond:"", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:""}"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on eth3): []"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on eth3): []"
time="2018-01-21T13:03:16Z" level=info msg="Running DHCP on eth0: dhcpcd -MA4 -e force_hostname=true -w --debug eth0"
time="2018-01-21T13:03:16Z" level=info msg="Running DHCP on eth3: dhcpcd -MA4 -e force_hostname=true -w --debug eth3"
time="2018-01-21T13:03:16Z" level=info msg="Running DHCP on eth1: dhcpcd -MA4 -e force_hostname=true -w --debug eth1"
time="2018-01-21T13:03:16Z" level=info msg="Running DHCP on eth2: dhcpcd -MA4 -e force_hostname=true -w --debug eth2"
time="2018-01-21T13:03:16Z" level=info msg="Checking to see if DNS was set by DHCP"
time="2018-01-21T13:03:16Z" level=info msg="dns testing lo"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease lo: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=info msg="dns testing eth0"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease eth0: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=info msg="dns testing eth1"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease eth1: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=info msg="dns testing eth2"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease eth2: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=info msg="dns testing eth3"
time="2018-01-21T13:03:16Z" level=error msg="exit status 1"
time="2018-01-21T13:03:16Z" level=debug msg="getDhcpLease eth3: "
time="2018-01-21T13:03:16Z" level=debug msg="line: []"
time="2018-01-21T13:03:16Z" level=debug msg="runCmds(on ): []"
time="2018-01-21T13:03:16Z" level=info msg="Writing default resolv.conf - no user setting, and no DHCP setting"
time="2018-01-21T13:03:16Z" level=debug msg="Resolve.conf == [nameserver 8.8.8.8
nameserver 8.8.4.4
], %!s(<nil>)"
time="2018-01-21T13:03:16Z" level=info msg="Apply Network Config SyncHostname"
[rancher@rancher boot]$
```

**Comment by niusmallnan** [comment] 2018-01-22 15:42
@lanchongyizu 
Hi, have you tried this? https://github.com/rancher/os/issues/2144#issuecomment-359033372
You need to update your iPXE file.

**Comment by lanchongyizu** [comment] 2018-01-23 03:14
@niusmallnan We(https://github.com/RackHD) had our own customized microkernel before, and migrated to RacherOS several months ago. We don't want to specify which NIC to be used for IPXE boot, since we don't know which NIC our users will use for IPXE boot. Before, the NICs are tried one by one in our microkernel, and only the one connected with RackHD will get the IPXE file.

What should we do with RacherOS to meet the above requirements? Thanks.

**Comment by niusmallnan** [comment] 2018-01-25 10:00
Duplicate of #2144 
Close this one.

**Closed by niusmallnan** 2018-01-25 10:00 UTC
Labels: area/networking, kind/bug
