### ISSUE TITLE
Problems installing Rancher OS in docker-machine (old)

### ISSUE THREAD

**Issue by JJ** [rancher/os#1479] opened 2016-12-22 17:11 UTC
**RancherOS Version: v0.8.0-rc2**

**Where are you running RancherOS? docker-machine + virtualbox 4.3.36**

I'm getting this error, repeatedly:
~~~
sudo docker-machine create -d virtualbox --virtualbox-boot2docker-url ~/Descargas/rancheros.iso cowgirl
Running pre-create checks...
(cowgirl) You are using version 4.3.36_Ubuntur105129 of VirtualBox. If you encounter issues, you might want to upgrade to version 5 at https://www.virtualbox.org
(cowgirl) Boot2Docker URL was explicitly set to "/home/jmerelo/Descargas/rancheros.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(cowgirl) Boot2Docker URL was explicitly set to "/home/jmerelo/Descargas/rancheros.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(cowgirl) Downloading /home/jmerelo/.docker/machine/cache/boot2docker.iso from /home/jmerelo/Descargas/rancheros.iso...
(cowgirl) Creating VirtualBox VM...
(cowgirl) Creating SSH key...
(cowgirl) Starting the VM...
(cowgirl) Check network to re-create if needed...
(cowgirl) Waiting for an IP...
Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
~~~

**Comment by joshwget** [comment] 2016-12-23 01:36
Is Vagrant relevant here? It looks like you're using Docker Machine.

Seems like a duplicate of #1475.

**Comment by JJ** [comment] 2016-12-23 06:31
Right, corrected. I don't know what I was thinking about.

**Comment by SvenDowideit** [comment] 2017-01-20 12:02
#1535 should go some way to fixing this (It'll be in 0.8.0-rc5 which I'll make this weekend)

**Comment by JJ** [comment] 2017-01-20 12:15
OK, will download and give it a try.

**Comment by SvenDowideit** [comment] 2017-01-22 13:15
https://github.com/rancher/os/releases/tag/v0.8.0-rc5 should fix the docker-machine creation problems.

**Closed** 2023-01-22 09:30 UTC
