### ISSUE TITLE
Network configuration broken after update 0.8.1 -> 0.9.0 

### ISSUE THREAD

**Issue by kuhnroyal** [rancher/os#1705] opened 2017-03-18 11:10 UTC
**RancherOS Version: (ros os version)**
0.9.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal

```
rancher:
  console: ubuntu
  network:
    interfaces:
      eth0:
        address: 192.168.1.25/24
        gateway: 192.168.1.1
        dhcp: false
```

I did an upgrade on 2 machines with `sudo ros os upgrade`. Both are configured to have a static IP address for `eth0` and dhcp disabled. After the reboot they both have 2 IPs, the static one and one given via dhcp.

I can ping and ssh with both IP's but they use the dhcp IP for outgoing communication which breaks a lot of things in my network. `ifconfig` show the dhcp IP bound to `eth0`.

After a downgrade to `v0.8.1` it works normal again. 

**Edit**
After the downgrade the IP's are fixed but all my docker local volumes are gone...

**Comment by SvenDowideit** [comment] 2017-03-19 01:43
argh. yup. 0.9.1 :/

**Comment by jdel** [comment] 2017-03-23 12:59
I can confirm I experience the same issue on a virtual box machine with two network interfaces.

At every boot, one of the two interfaces (random) gets an IP from DHCP, then gets a secondary IP with the one configured through the cloud-config file.

The issue doesn't occur with rancher/os:v0.8.1

**Comment by SvenDowideit** [comment] 2017-03-27 02:03
this should be resolved in v0.9.1 - please repoen, or open a new PR is you find otherwise :)

**Comment by kuhnroyal** [comment] 2017-03-28 11:29
Still happening in 0.9.1

**Comment by seru1337** [comment] 2017-03-29 12:11
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Virtual Server

Did a clean install of 0.9 and 0.9.1 and had the same problem. Installed 0.8.1 and everything worked as expected.

**Comment by SvenDowideit** [comment] 2017-03-29 12:20
@kuhnroyal @seru1337 mmm. Can you please post the output of `ip a`? I'm also curious what files you see in `/var/lib/rancher/conf` (as root), and their content.

**Comment by kuhnroyal** [comment] 2017-03-29 12:53
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether a2:18:09:a1:50:8f brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.151/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.1.29/24 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a018:9ff:fea1:508f/64 scope link 
       valid_lft forever preferred_lft forever
```

It is supposed to have the static IP `192.168.1.29`.

**Comment by seru1337** [comment] 2017-03-29 15:50
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:e4:fd:4a brd ff:ff:ff:ff:ff:ff
    inet 192.168.63.159/24 brd 192.168.63.255 scope global eth0
      valid_lft forever preferred_lft forever
    inet 192.168.63.213/24 scope global secondary eth0
      valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fee4:fd4a/64 scope link
      valid_lft forever preferred_lft forever
/var/lib/rancher/conf

    drwx------    3 root     root          4096 Mar 29 15:15 .
    drwxr-xr-x    6 root     root          4096 Mar 29 15:15 ..
    drwx------    2 root     root          4096 Mar 29 14:33 cloud-config.d
    -rw--w----    1 root     root          4843 Mar 29 15:15 cloud-config.yml
    cloud-config.yml contains ssh-key information, in cloud-config.d:
    drwx------    2 root     root          4096 Mar 29 14:33 .
    drwx------    3 root     root          4096 Mar 29 15:15 ..
    -rw--w----    1 root     root            70 Mar 29 14:33 init.yml
    -rw-r--r--    1 root     root           606 Mar 29 15:14 user_config.yml
    [root@test-bug cloud-config.d]# cat init.yml
    EXTRA_CMDLINE: /init
    rancher:
      environment:
        EXTRA_CMDLINE: /init
    [root@test-bug cloud-config.d]# cat user_config.yml
    #cloud-config
    hostname: test-bug
    rancher:
      network:
        interfaces:
          eth0:
            address: 192.168.63.213/24
            dhcp: false
        gateway: 192.168.63.1
            mtu: 1500
    ssh_authorized_keys:
     - ssh-rsa xxx
I can reproduce the bug with endless virtual machines and it doesnt matter if i configure the ethernet via ros commands or directly in the file.
When i checked ifconfig it displayed the DHCP address as eth0, when i started the machine without the ethernet adapter it displayed the defined static IP but once enabled I could connect via either IP.

**Comment by Rabie-Zamane** [comment] 2017-03-30 06:19
We have the same issue described here and we had to downgrade to v0.8.1 to be able to work with our RancherOS machines.
We can connect to the Machines using ssh and the configured IP but ifconfig shows a dhcp-IP.
Looks like RancherOS does some NAT between the configured IP and the one served by the dhcp-server.

**Comment by SvenDowideit** [comment] 2017-03-30 10:36
this is mega frustrating - with every 0.9.x version I use, I can pxe boot my notebook (at which point it gets 10.10.10.32) with a cloud-config that has 10.10.10.41 in it, and by the time that i log in, eth0 has only 10.10.10.41.

I obviously need to keep trying different things, but argh!

no, its not NAT, on boot, to enable it to get a possible remote cloud-init, we start the network with default (or /proc/cmdline) bases config. then we read all the requested cloud-config's, and reapply that to the network. in 0.9.x, this code was changed to make fewer assumptions, and to run `dhcp --release` on devices that change to `dhcp: false`

but obviously, this isn't working for all cases.

**Comment by SvenDowideit** [comment] 2017-03-30 11:25
finally, I have a vm that does have the problem. 🏆  🐢

**Comment by SvenDowideit** [comment] 2017-03-30 14:29
its not much progress, but 

```
> time="2017-03-30T14:22:31Z" level=debug msg=RunDhcp
> time="2017-03-30T14:22:31Z" level=info msg="Running DHCP on eth2: dhcpcd -MA4 -e force_hostname=true eth2"
> time="2017-03-30T14:22:31Z" level=info msg="Running DHCP on eth0: dhcpcd --release eth0"
> time="2017-03-30T14:22:31Z" level=info msg="Running DHCP on eth1: dhcpcd --release eth1"
sending commands to master dhcpcd process
sending commands to master dhcpcd process
> time="2017-03-30T14:22:31Z" level=error msg="signal: segmentation fault"
```

**Comment by SvenDowideit** [comment] 2017-04-01 12:14
@kuhnroyal @seru1337 @Rabie-Zamane can you guys please do me a favour and upgrade a sacrificial system with

`sudo ros os upgrade -f -i zombie/os:network --append "rancher.debug=true rancher.autologin=tty1 rancher.auto login=ttyS0 printk.devkmsg=on rancher.password=justincase"`

and then send me the output of `dmesg` and `ip a` and `sudo system-docker logs network`?

I keep thinking I'm getting somewhere with this, but then it breaks some other corner case.

**Comment by SvenDowideit** [comment] 2017-04-02 10:52
and if you can do the same with the `zombie/os:net2` image that might help me too - from my testing so far, this one removes the extra IP's, but it also breaks networking on some systems - so i need to track that down.

**Comment by SvenDowideit** [comment] 2017-04-02 11:49
UPDATE: just try `net2`

@kuhnroyal @seru1337 @Rabie-Zamane can you guys please do me a favour and upgrade a sacrificial system with

`sudo ros os upgrade -f -i zombie/os:net2 --append "rancher.debug=true rancher.autologin=tty1 rancher.auto login=ttyS0 printk.devkmsg=on rancher.password=justincase"`

and then send me the output of `dmesg` and `ip a` and `sudo system-docker logs network`?

I keep thinking I'm getting somewhere with this, but then it breaks some other corner case.

**Comment by kuhnroyal** [comment] 2017-04-02 14:29
It works with the net2 image.

```
[rancher@example ~]$ sudo system-docker logs network
> time="2017-04-02T13:58:28Z" level=info msg="Apply Network Config" 
> time="2017-04-02T13:58:28Z" level=debug msg="Config: &netconf.NetworkConfig{PreCmds:[]string(nil), DNS:netconf.DNSConfig{Nameservers:[]string{\"192.168.1.5\", \"192.168.178.1\"}, Search:[]string{\"example.lan\"}}, Interfaces:map[string]netconf.InterfaceConfig{\"eth0\":netconf.InterfaceConfig{Match:\"\", DHCP:false, DHCPArgs:\"\", Address:\"192.168.1.29/24\", Addresses:[]string(nil), IPV4LL:false, Gateway:\"192.168.1.1\", GatewayIpv6:\"\", MTU:0, Bridge:\"\", Bond:\"\", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:\"\"}, \"lo\":netconf.InterfaceConfig{Match:\"\", DHCP:false, DHCPArgs:\"\", Address:\"\", Addresses:[]string{\"127.0.0.1/8\", \"::1/128\"}, IPV4LL:false, Gateway:\"\", GatewayIpv6:\"\", MTU:0, Bridge:\"\", Bond:\"\", BondOpts:map[string]string(nil), PostUp:[]string(nil), PreUp:[]string(nil), Vlans:\"\"}}, PostCmds:[]string(nil), HTTPProxy:\"\", HTTPSProxy:\"\", NoProxy:\"\"}" 
> time="2017-04-02T13:58:28Z" level=info msg="Applying 127.0.0.1/8 to lo" 
> time="2017-04-02T13:58:28Z" level=info msg="Applying ::1/128 to lo" 
> time="2017-04-02T13:58:28Z" level=info msg="Applying 192.168.1.29/24 to eth0" 
> time="2017-04-02T13:58:28Z" level=info msg="Set 192.168.1.29/24 on eth0" 
> time="2017-04-02T13:58:28Z" level=info msg="removing  192.168.1.151/24 eth0 from eth0" 
> time="2017-04-02T13:58:28Z" level=info msg="Removed 192.168.1.151/24 eth0 from eth0" 
> time="2017-04-02T13:58:28Z" level=info msg="removing  fe80::a018:9ff:fea1:508f/64 from eth0" 
> time="2017-04-02T13:58:28Z" level=info msg="Removed fe80::a018:9ff:fea1:508f/64 from eth0" 
> time="2017-04-02T13:58:28Z" level=info msg="Added default gateway 192.168.1.1" 
> time="2017-04-02T13:58:28Z" level=info msg="Apply Network Config RunDhcp" 
> time="2017-04-02T13:58:28Z" level=debug msg=RunDhcp 
> time="2017-04-02T13:58:28Z" level=info msg="Running DHCP on eth0: dhcpcd --release eth0" 
dhcpcd not running
> time="2017-04-02T13:58:28Z" level=error msg="exit status 1" 
> time="2017-04-02T13:58:28Z" level=info msg="Apply Network Config SyncHostname" 


[rancher@example ~]$ sudo ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether a2:18:09:a1:50:8f brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.29/24 scope global eth0
       valid_lft forever preferred_lft forever
3: docker-sys: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 172.18.42.2/16 scope global docker-sys
       valid_lft forever preferred_lft forever
    inet6 fe80::e86f:5cff:fe5c:c2ed/64 scope link 
       valid_lft forever preferred_lft forever
5: br-70681e3dc57d: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:47:31:2e:02 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 scope global br-70681e3dc57d
       valid_lft forever preferred_lft forever
    inet6 fe80::42:47ff:fe31:2e02/64 scope link 
       valid_lft forever preferred_lft forever
6: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:81:b6:7d:17 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:81ff:feb6:7d17/64 scope link 
       valid_lft forever preferred_lft forever
18: veth0b90e98@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 42:ed:6b:30:2a:8f brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::40ed:6bff:fe30:2a8f/64 scope link 
       valid_lft forever preferred_lft forever
```

`dmesg` output is a lot...

**Comment by SvenDowideit** [comment] 2017-04-02 21:57
awesome! we still have the problem that at some point, dhcpcd seg faults - I'm going to plan on making an 0.9.3-rc tonite to make sure things combine reasonably.

**Comment by kuhnroyal** [comment] 2017-04-04 09:30
0.9.2-rc1 works

**Comment by SvenDowideit** [comment] 2017-04-06 22:28
@kuhnroyal @seru1337 @Rabie-Zamane if you could try https://github.com/rancher/os/releases/tag/v0.9.2-rc2 that would be awesome - the fixes for this issue have caused problems on m and r type vm's on aws, so I've had to try a change, and I need some idea if that breaks your setup (it breaks a hosted setup of mine, but its different to yours)

**Comment by Waret** [comment] 2017-04-07 01:45
VM on ESXi 6.0, rancher os v0.9.1
[rancher@rancheros-cd01 ~]$ sudo system-docker logs network
> time="2017-04-07T01:41:20Z" level=error msg="symlink /usr/bin/ros /usr/bin/cloud-init-execute: file exists"
> time="2017-04-07T01:41:20Z" level=error msg="symlink /usr/bin/ros /usr/bin/cloud-init-save: file exists"
> time="2017-04-07T01:41:20Z" level=error msg="symlink /usr/bin/ros /usr/bin/dockerlaunch: file exists"
> time="2017-04-07T01:41:20Z" level=error msg="symlink /usr/bin/ros /usr/bin/respawn: file exists"
> time="2017-04-07T01:41:20Z" level=error msg="symlink /usr/bin/ros /usr/bin/system-docker: file exists"
> time="2017-04-07T01:41:20Z" level=error msg="symlink /usr/bin/ros /usr/sbin/netconf: file exists"
> time="2017-04-07T01:41:20Z" level=error msg="symlink /usr/bin/ros /usr/sbin/wait-for-docker: file exists"
> time="2017-04-07T01:41:20Z" level=info msg="Apply Network Config"
> time="2017-04-07T01:41:20Z" level=info msg="Applying 127.0.0.1/8 to lo"
> time="2017-04-07T01:41:20Z" level=info msg="Applying ::1/128 to lo"
> time="2017-04-07T01:41:20Z" level=info msg="Applying 192.168.1.60/24 to eth0"
> time="2017-04-07T01:41:20Z" level=info msg="Set 192.168.1.60/24 on eth0"
> time="2017-04-07T01:41:20Z" level=info msg="leaving  192.168.1.166/24 eth0 from eth0"
> time="2017-04-07T01:41:20Z" level=info msg="leaving  fe80::20c:29ff:fe18:b8d4/64 from eth0"
> time="2017-04-07T01:41:20Z" level=info msg="Added default gateway 192.168.1.1"
> time="2017-04-07T01:41:20Z" level=info msg="Running DHCP on eth0: dhcpd --release --nohook resolv.conf eth0"
> time="2017-04-07T01:41:20Z" level=error msg="exec: \"dhcpd\": executable file not found in $PATH"
> time="2017-04-07T01:41:20Z" level=info msg="Running DHCP on lo: dhcpd --release --nohook resolv.conf lo"
> time="2017-04-07T01:41:20Z" level=error msg="exec: \"dhcpd\": executable file not found in $PATH"


[rancher@rancheros-cd01 ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:18:b8:d4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.166/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.1.60/24 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe18:b8d4/64 scope link
       valid_lft forever preferred_lft forever
3: docker-sys: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 172.18.42.2/16 scope global docker-sys
       valid_lft forever preferred_lft forever
    inet6 fe80::48d0:aff:fe61:db1f/64 scope link
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:4c:70:4d:59 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever

**Comment by Waret** [comment] 2017-04-07 02:01
VM on ESXi6.0, with rancheros-v0.9.2-rc2, problem solved.

```shell
[rancher@rancher ~]$ sudo system-docker logs network
> time="2017-04-07T02:00:12Z" level=info msg="Apply Network Config"
Failed to write to log, write /dev/kmsg: invalid argument
> time="2017-04-07T02:00:12Z" level=info msg="Applying 127.0.0.1/8 to lo"
> time="2017-04-07T02:00:12Z" level=info msg="Applying ::1/128 to lo"
> time="2017-04-07T02:00:13Z" level=info msg="Applying 192.168.1.61/24 to eth0"
> time="2017-04-07T02:00:13Z" level=info msg="Set 192.168.1.61/24 on eth0"
> time="2017-04-07T02:00:13Z" level=info msg="removing  192.168.1.167/24 eth0 from eth0"
> time="2017-04-07T02:00:13Z" level=info msg="Removed 192.168.1.167/24 eth0 from eth0"
> time="2017-04-07T02:00:13Z" level=info msg="removing  fe80::20c:29ff:fe34:2887/64 from eth0"
> time="2017-04-07T02:00:13Z" level=info msg="Removed fe80::20c:29ff:fe34:2887/64 from eth0"
> time="2017-04-07T02:00:13Z" level=info msg="Added default gateway 192.168.1.1"
> time="2017-04-07T02:00:13Z" level=info msg="Apply Network Config RunDhcp"
> time="2017-04-07T02:00:13Z" level=info msg="Running DHCP on eth0: dhcpcd --release eth0"
dhcpcd not running
> time="2017-04-07T02:00:13Z" level=error msg="exit status 1"
> time="2017-04-07T02:00:13Z" level=info msg="Apply Network Config SyncHostname"
[rancher@rancher ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:34:28:87 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.61/24 scope global eth0
       valid_lft forever preferred_lft forever
3: docker-sys: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 172.18.42.2/16 scope global docker-sys
       valid_lft forever preferred_lft forever
    inet6 fe80::945f:83ff:fe98:fca5/64 scope link
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:a3:20:87:ee brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by SvenDowideit** [comment] 2017-04-07 10:00
and tonite I make an rc3 which should also not re-break this (ok, this time its extremely unlikely to cause problems)

**Comment by kuhnroyal** [comment] 2017-04-07 10:53
rc2 is working as well for me

**Comment by joshuacox** [comment] 2017-04-24 15:25
upgraded 1.0.0 on my dual NIC stack and I'm back to only one interface working, rolling back to 0.9.2 here

**Comment by SvenDowideit** [comment] 2017-04-24 15:29
@joshuacox that's bizarre - 1.0.0 is identical to 0.9.2 - the only 2 changes are the number, and the default version of user-docker.

**Comment by joshuacox** [comment] 2017-04-24 15:31
bah humbug 0.9.2 is broken for me too, rolling back to 0.9.1 fixed it for me and I now have two working NICs in separate networks again.  I think I upgraded from 0.9.0 :( sorry for not keeping up (the more 'production' these things become the more I fear upgrading them)

**Comment by SvenDowideit** [comment] 2017-04-24 16:01
@joshuacox I get the feeling that your report should be in a different issue?

**Comment by SvenDowideit** [comment] 2017-06-19 05:07
closing - as this initial issue has been improved - and continuing in #1812

**Closed by SvenDowideit** 2017-06-19 05:07 UTC
Labels: status/pr-submitted
