### ISSUE TITLE
Support private registry service image pulls in cloud-init

### ISSUE THREAD

**Issue by ekristen** [rancher/os#775] opened 2016-02-23 23:04 UTC
The docs say this is not possible, I'd be more than willing to help contribute to the project if someone can point me in the right direction in how to make this possible.

**Comment by ekristen** [comment] 2016-03-02 15:52
Any guidance on this? I'm very interested in helping figuring out how to make this happen. Thanks!

**Comment by dexterddit** [comment] 2016-03-30 07:10
Any ETA for this ?

**Comment by ekristen** [comment] 2016-03-30 18:11
@deniseschannon hate to bother you, but any idea if anyone is looking into this or if someone has an idea there at Rancher at where the problem is? I'm definitely willing to contribute. Thanks!

**Comment by joshwget** [comment] 2016-03-30 22:18
Unfortunately there isn't anybody currently working on this so we don't really have an ETA. I'm not very familiar with how private registries work, otherwise I'd try to point you in the right direction. If you do decide to try and take a look at implementing this, I'm definitely willing to help through any specific issues you run into!

**Comment by ekristen** [comment] 2016-03-30 22:42
@joshwget there is nothing special about private registries vs a public registry other than they generally require username/password, which means a `.docker/config.json` populated someplace.

Obviously this is a known issue because you all mention in the docs, so I assume someone at Rancher knows where the limitation is. Perhaps in cloud-init or someplace else. Just trying to find a place to start if possible.

**Comment by joshwget** [comment] 2016-03-30 23:51
Okay, I think I have a somewhat better idea of what's required then.

The cloud config struct has to be updated to include fields for Docker authorizations https://github.com/rancher/os/blob/master/config/types.go#L106. The config struct in Docker from Scratch would have to have similar fields https://github.com/rancher/docker-from-scratch/blob/master/scratch.go#L49. 

Then the authorizations would have to be transferred from the cloud config to the Docker from Scratch config https://github.com/rancher/os/blob/master/init/init.go#L162.

Lastly, Docker from Scratch should convert the authorizations from its config to the JSON format that Docker recognizes and write it to a file. By default Docker looks in `$HOME/.docker`, but it's probably better to save this file somewhere else and then use the `--config` argument to let Docker know where it is.

**Comment by ekristen** [comment] 2016-03-31 00:40
Awesome @joshwget this is great info thanks, guess I need to figure out how to build all this stuff now.

**Comment by ekristen** [comment] 2016-03-31 00:48
> but it's probably better to save this file somewhere else and then use the --config argument to let Docker know where it is.

I'm not sure this makes sense? It's the docker client that uses `$HOME/.docker/config.json` not the daemon. So I'm not sure the docker from scratch needs to be touched? But I could misunderstand how it is being used. 

I think that it has mostly to do with getting the information in play for when the cloud init for rancher os downloads images for rancher services. 

Thoughts?

**Comment by ekristen** [comment] 2016-05-02 19:34
@joshwget in IRC you said this was all but complete except for an update to libcompose? Is there an issue that is being tracked in?

**Comment by dexterddit** [comment] 2016-05-05 07:26
@joshwget does this mean i can pull the rancher images using my private registry ?

**Comment by joshwget** [comment] 2016-05-05 15:58
@ekristen There isn't currently an issue tracking it. I'm nearly done with the update, but unfortunately it might not make it in v0.4.5. It'll introduce a lot of changes and we'd like more time to test and make sure it doesn't break things.

**Comment by deniseschannon** [comment] 2016-05-05 21:08
We have decided to move this into v0.5.0 due to the extent of changes that syncing with libcompose (a requirement).

**Comment by ekristen** [comment] 2016-05-06 13:59
:(

**Comment by joshwget** [comment] 2016-06-30 17:19
Confirmed with rancher/os:v0.5.0-rc2

**Closed by joshwget** 2016-06-30 17:19 UTC
Labels: kind/enhancement, priority/p0, status/to-test

**Comment by ekristen** [comment] 2016-06-30 21:17
This is awesome news, +1 I will check it out ASAP.

**Comment by joshwget** [comment] 2016-06-30 22:14
Thanks @ekristen. There's an example in the PR, still working on some docs for it.

**Comment by dexterddit** [comment] 2016-08-22 07:52
Thanks for the feature ...

**Comment by chinaares** [comment] 2016-09-02 08:58
I use this configure：
#cloud-config
rancher:
  user_docker:
    args: [daemon, --log-opt, max-size=25m, --log-opt, max-file=2, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock', --userland-proxy=false, --insecure-registry, '192.161.14.101:81',  --registry-mirror, 'http://192.161.14.101:81']
  system_docker:
    args: [daemon, --log-opt, max-size=25m, --log-opt, max-file=2, -s, overlay, --restart=false, -g, /var/lib/system-docker, -G, root, -p /var/run/system-docker.pid, --exec-root=/var/run/system-docker, --config-file=/etc/docker/system-daemon.json, -H, 'unix:///var/run/system-docker.sock', --userland-proxy=false,--insecure-registry, '192.161.14.101:81', --registry-mirror, 'http://192.161.14.101:81']
........

but when i excute command, the private mirror not be applied:
# sudo ros install -f -c cloud_config.yml -d /dev/vda -no-reboot

**Comment by deniseschannon** [comment] 2016-09-02 21:22
@chinaares Please look into using @joshwget's cloud config validator as your cloud config has errors. 

https://forums.rancher.com/t/online-cloud-config-validator/3530

Note: I added 3 backticks in front and after your code to make it a code block.

**Comment by chinaares** [comment] 2016-09-04 02:05
@deniseschannon Than you for your reply!
Yes, I use cloud config validator to found 2 "--log-opt error"  ,and I had remove "--log-opt, max-file=2".
Then, RancherOS cloud-config validator tell me "Valid!".
But, when I fix the yml file error and run command:
# sudo ros install -f -c cloud_config.yml -d /dev/vda -no-reboot
the mirror registry still not work !
Any help would be appreciated.
