### ISSUE TITLE
Unable to mount within a container even w/ `--cap-add=SYS_ADMIN`

### ISSUE THREAD

**Issue by albertdb** [rancher/os#940] opened 2016-05-16 14:31 UTC
**RancherOS Version: v0.4.3 & v0.4.5**

**Where are you running RancherOS? Openstack & AWS**

According to docker run reference, it should be possible to enable mount syscall on Docker containers w/ `--cap-add=SYS_ADMIN` but it doesn't work on RancherOS.

There is an[ issue](https://github.com/docker/docker/issues/16429) in Docker repo and a [mail list thread ](https://groups.google.com/d/msg/docker-user/yC-S-_yN4P0/XGdCVjktBQAJ) that proposes a solution (the problem there is AppArmor/SELinux related) but it doesn't work on RancherOS. Mainly because, correct me if I'm wrong, RancherOS doesn't use by default AppArmor nor SELinux, so the problem shouldn't even appear.

Am I missing something? If not, is there any chance to have this solved?

Thank you very much.

**Comment by joshwget** [comment] 2016-05-23 04:19
This is likely a duplicate of #948, or vice versa. Closing in favor of that issue.

**Comment by albertdb** [comment] 2016-05-23 11:52
That issue affects v0.4.4 and up, but this one affects also v0.4.3. Are you sure it's the same issue?

I'm not executing `mount` in console (like on that issue), but on a user container w/ `--cap-add=SYS_ADMIN`

Unless v0.4.4+ console isn't a privileged container and on v0.4.3 it is, the reason why `mount` doesn't work cannot be the same in both issues.

**Comment by Rucknar** [comment] 2016-05-26 12:18
Docker 1.10 upwards implements a syscall firewall, as a result you need to make an allowance for the calls used by mounting. It might not be the same issue, but it's easy to test, run the container in privileged mode to see if it makes a difference.

**Comment by albertdb** [comment] 2016-05-26 13:12
In privileged mode it works, but giving that is like giving root permissions. I only want to give enough permissions to perform mount. In theory only CAP_SYS_ADMIN is needed, but it doesn't appear to be the case in RancherOS or Docker 1.10. That being said, CAP_SYS_ADMIN is not so different from giving root privileges...

**Comment by Rucknar** [comment] 2016-05-26 13:18
I agree @albertdb You can run without it, that was just a test. With docker 1.10 onwards, you need to be reading up on dockers new Seccomp Profiles. You will need to specify a custom seccomp profile to allow mount to work.

**Comment by albertdb** [comment] 2016-05-26 13:21
Thanks for the info, that is just what I was looking for.

**Comment by joshwget** [comment] 2016-06-17 18:20
@albertdb Sorry for closing this earlier! This does seem to be a separate issue. Were you able to resolve this, or do you still think there might be a problem in RancherOS?

**Comment by albertdb** [comment] 2016-06-18 10:12
@joshwget The issue persists, I'm afraid.

**Comment by batk0** [comment] 2016-07-11 19:01
The issue persists on v0.5.0.

**Comment by joshwget** [comment] 2016-11-07 18:27
I'm no longer able to reproduce this issue in v0.7.0. This was likely a kernel bug that was fixed since v0.5.0 was released. If anyone continues to run into this, please open another issue!

**Closed by joshwget** 2016-11-07 18:27 UTC
