### ISSUE TITLE
Allow removal of default log-opts

### ISSUE THREAD

**Issue by jhmartin** [rancher/os#1382] opened 2016-11-10 20:56 UTC
When setting log-opts with the new map structure at #1166 , such as to use awslogs, the existing max-size and max-file values are preserved which fails under alternate log handlers:

**RancherOS Version: (ros os version)**
0.7.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

```
rancher:
  docker:
    storage_driver: overlay
    group: docker
    userland_proxy: false
    log_driver: awslogs
    log_opts:
      awslogs-group: groupname
```
renders as
```
docker-init daemon --log-opt awslogs-group=groupname --log-opt max-file=2 --log-opt max-size=25m --group docker --log-driver awslogs --host unix:///var/run/docker.sock --userland-proxy=false --storage-driver overlay]"
```

**Comment by joshwget** [comment] 2016-11-10 23:57
You should be able to override them by setting them to empty.

```
log_opts:
  awslogs-group: groupname
  max-file: ""
  max-size: ""
```

At the same time, I'm not sure what value these defaults actually provide. We might be able to just remove these all together.

**Comment by deniseschannon** [comment] 2016-11-12 16:30
The defaults are good practice in case your logs fill up. I've seen it happen that logs can fill up quickly and without the max-file and max-size, they never roll over. 

Per the Docker docs:

```
Logs that reach max-size are rolled over. You can set the size in kilobytes(k), megabytes(m), or gigabytes(g). eg --log-opt max-size=50m. If max-size is not set, then logs are not rolled over.

max-file specifies the maximum number of files that a log is rolled over before being discarded. eg --log-opt max-file=100. If max-size is not set, then max-file is not honored.

If max-size and max-file are set, docker logs only returns the log lines from the newest log file.
```

**Comment by jhmartin** [comment] 2016-11-12 18:49
I agree the defaults are fine. I'll try that method for suppressing them.

**Comment by ryansch** [comment] 2016-11-17 23:30
@deniseschannon @joshwget I'm having this problem with 0.7.1.  I've tried setting the values to the empty string and verified with `ros config`.  I'm seeing this in the container logs for user docker:

`docker-init daemon --host unix:///var/run/docker.sock --group docker --storage-driver overlay --log-opt max-file= --log-opt max-size= --log-opt tag={{.Name}}/{{.ID}} --log-driver syslog`

It's still specifying those options.

**Comment by ryansch** [comment] 2016-11-17 23:37
I think the root cause is here: https://github.com/rancher/os/blob/7dce4d54c1ee591db6999d5c1ec402b824ae1182/config/docker_config.go#L49

That `range` isn't checking for empty values.

**Comment by joshwget** [comment] 2016-11-18 00:38
Good catch. I can't think of a use case where someone would set an empty value but still expect it to be in the generated argument list. Likely safe to filter these for maps and possibly for lists as well.

**Comment by ryansch** [comment] 2016-11-18 17:05
@joshwget Is there a possible workaround?  I was hoping to upgrade to 0.7.1 for the dirty cow patch.  To date I haven't been able to figure out all the pieces required to build a custom version of rancheros.

**Comment by SvenDowideit** [comment] 2016-11-18 22:58
Because you're "only" wanting to change go code that goes into the `ros` tool, you should be able to use `make` in this repository. 

The painful bit is that the build uses git to determine what the iso's version number is based on the current commit's tag (or dirty-ness). (and it thenuses that to either get that release's os-services yaml files, or those from master)

if you make your change and commit it locally, then tag it with `v0.7.1`,the resulting iso should think its a proper release.
The other way, (and the more proper way) is to change the config to point to the v0.7.0 release without fudging the tag - but I've not done this yet, so IDK is there are any pain points.

the 2 keys i can think of are `rancher.repositories.core.url` and (i think) `rancher environment.version`.

(I'd change the url to my own fork of `rancher/os-services` and then push all the images to it - especially the `rancher/os:...` installer image.

I think I'll be working in this area next week - so hopefully it'll become simpler.

**Comment by ryansch** [comment] 2016-11-21 17:23
I'll stay tuned.

**Comment by brettneese** [comment] 2016-12-22 23:16
Any update on this? Running into it myself. We're using the AWS AMIs, so not sure I can do the workarounds mentioned by @SvenDowideit

**Comment by ryansch** [comment] 2016-12-22 23:18
@brettneese We're still on 0.6.1 until 0.8.0 is released with a fix for this.

**Comment by brettneese** [comment] 2016-12-22 23:36
@ryansch excellent, thanks. I'm only working on getting together a staging environment right now anyway. Hoping that 0.8.0 with this fix comes up sometime within the next few weeks, though.

**Comment by joshwget** [comment] 2016-12-23 00:05
@brettneese You could try out v0.8.0-rc2, depending on your needs. Unfortunately, I don't think there's a workaround to this in v0.7.0 or v0.7.1

**Comment by brettneese** [comment] 2016-12-23 00:45
@joshwget unfortunately there are no AMIs for 0.80, and it's not worth bundling one up myself. ;-)

**Comment by deniseschannon** [comment] 2017-01-19 07:06
Verified with v0.8.0-rc4

Launched AMI with this cloud-config:

```
#cloud-config
rancher:
  docker:
    log_driver: syslog
    log_opts:
      tag: '{{.Name}}/{{.ID}}'
      max-file: ''
      max-size: ''
```

After launching the AMI,

```
$ system-docker logs docker
> time="2017-01-19T06:46:15Z" level=info msg="Running [docker-runc exec -- d4bba53a65049e372381e5fb3b5a0106eedaddcbde759959ec8a851806f9d626 env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=ip-172-31-14-77.us-west-1.compute.internal HOME=/ ros docker-init daemon --host unix:///var/run/docker.sock --log-opt tag={{.Name}}/{{.ID}} --storage-driver overlay --log-driver syslog --group docker]" 
```

**Closed by deniseschannon** 2017-01-19 07:06 UTC
Labels: status/to-test
