### ISSUE TITLE
Issues with preloading system-docker images

### ISSUE THREAD

**Issue by lucymhdavies** [rancher/os#1698] opened 2017-03-15 12:37 UTC
**RancherOS Version: (ros os version)**
v0.8.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VMWare (ESXi)

----

At what point during the boot process are pre-packed docker images loaded?

https://docs.rancher.com/os/configuration/prepacking-docker-images/
just says

> On boot, RancherOS scans /var/lib/rancher/preload/docker and /var/lib/rancher/preload/system-docker directories and tries to load container image archives it finds there, with docker load and system-docker load.

We have an issue at the moment where we are pre-packing some docker images for system-docker, for VMs that do not have internet access. We have these services defined in our cloud-init.

However, when we boot the VMs, we see that system-docker is attempting to pull the images down from docker hub.

Once we are able to log in to the VM, we are able to run `ros service up my_service` and all is well.

So my current theory is that the pre-loading process takes place after cloud-init has run, at which point the images would not yet have been loaded into system-docker.

This appears contrary to what is written in
https://docs.rancher.com/os/system-services/built-in-system-services/

Can you confirm whether or not that wiki page is up to date with the changes for early cloud-init?
The history of the page does not seem to indicate that it has been updated besides the sysctl changes and formatting:
https://github.com/rancher/rancher.github.io/commits/master/os/system-services/built-in-system-services/index.md

And if that wiki page is not up-to-date, and cloud-init does indeed run earlier than pre-loading the docker images, would it be possible to move the image pre-loading sooner in the boot process?

**Comment by SvenDowideit** [comment] 2017-04-27 23:00
eeek, how did i miss this question? (I'm guessing some things were moved around and no tests failed)

**Comment by SvenDowideit** [comment] 2017-04-27 23:35
@lucymhdavies I wonder if you can give us a look at the boot log (dmesg should have something since 0.9), and the cloud-init

the built-in-system-services is quite a bit out of date, but from my poking around, it looks to me like we're still loading the preload .tar right after we start the real system-docker (cloud-init have been moved around, and does indeed run before the real system-docker starts.

**Comment by SvenDowideit** [comment] 2017-04-28 00:29
and in the process of looking into this, I made and merged https://github.com/rancher/os/pull/1826/files

removing that docs page - because it was out of date - it doesn't really look like we've got a new document covering the order atm :/

**Comment by lucymhdavies** [comment] 2017-05-08 12:06
Hi!

I've been away from work for a while. Just built a v1.0.1 VM template to try this on.

Just had a look at the dmesg, and you're right, it does look like it's loading the image prior to starting the service.

```
[   18.642092] INFO[0000] Loading image /var/lib/rancher/preload/system-docker/rancher_os_openvmtools_v1.0.1.tar.gz

[   26.559641] INFO[0008] [11/17] [open-vm-tools]: Starting

[   67.093324] ERRO[0048] Failed Starting open-vm-tools : Error: No such image: rancher/os-openvmtools:v1.0.1
[   67.093591] ERRO[0048] Failed to start: open-vm-tools : Error: No such image: rancher/os-openvmtools:v1.0.1
```

[dmesg.txt](https://github.com/rancher/os/files/983371/dmesg.txt)
[ros-config-export.txt](https://github.com/rancher/os/files/983372/ros-config-export.txt)

**Comment by lucymhdavies** [comment] 2017-08-30 15:10
Just checked this in RancherOS v1.0.4, and we're getting the same issue.

i.e. it pre-loads the `rancher/os-openvmtools:v1.0.4` image, but then cannot find the image when it attempts to start the container.

This original issue was raised as a Question. Given it would appear that there is a bug in RancherOS, do you want me to raise this again as a bug?

**Comment by lucymhdavies** [comment] 2017-08-30 15:42
I have discovered that importing the images manually seems to work.

i.e. by running

```
system-docker import /var/lib/rancher/preload/system-docker/*.tar.gz
```

This seems to rule out any problems importing the image.

I suppose as a workaround, I may be able to run that command as part of `runcmd`.


I should note that images pre-loaded into `docker` work fine. It's just `system-docker` which isn't working.

**Comment by lucymhdavies** [comment] 2017-08-31 17:30
I've had another look through the open issues.

https://github.com/rancher/os/pull/2001 looks like it's possibly a fix for my issue.

I'll give it another try in RancherOS 1.1.0-rc3

**Comment by SvenDowideit** [comment] 2017-09-05 00:33
it really wouldn't surprise me if your issue is different - but I hop you're right :) v1.1.0 just ran out the door, and I'm in the middle of taking everything apart - lmk :)

**Comment by SvenDowideit** [comment] 2017-09-05 00:35
the other thing that might help us, it that v1.1 logs alot more info - and the early boot phase logs are now in `/var/log/boot` (instead of console only)

**Comment by lucymhdavies** [comment] 2017-11-13 14:20
Took us a while, but actually trying out the latest RancherOS for VMWare machines this sprint.

I'll hopefully have some good news very soon (or at the very least, some boot logs)

**Comment by lucymhdavies** [comment] 2017-11-14 15:49
Well, the good news is that it would appear images ARE being pre-loaded into system-docker now.
With more logs, maybe we can figure this out.

So image was pre-loaded
```
[root@rancher boot]# ls /var/lib/rancher/preload/system-docker/
rancher_os_openvmtools_v1.1.0.tar.gz       rancher_os_openvmtools_v1.1.0.tar.gz.done

[root@rancher ~]# system-docker images | grep openvm
rancher/os-openvmtools      v1.1.0              adc859ab7307        11 weeks ago        165 MB
```

But we still get the "no such image" error


```
[root@rancher ~]# cat /var/log/boot/ros-sysinit.log  | grep -C 2 vm
], %!s(<nil>)"
time="2017-11-14T15:33:25Z" level=info msg="Exec [/usr/bin/ros-sysinit]"
time="2017-11-14T15:33:25Z" level=info msg="Loading image /var/lib/rancher/preload/system-docker/rancher_os_openvmtools_v1.1.0.tar.gz"
time="2017-11-14T15:33:27Z" level=info msg="[1/4] Starting loadImages"
time="2017-11-14T15:33:27Z" level=debug msg="Looking for images at /usr/share/ros"
--
time="2017-11-14T15:33:33Z" level=debug msg="[0/16] [console]: Adding "
time="2017-11-14T15:33:33Z" level=debug msg="[0/16] [container-data-volumes]: Adding "
time="2017-11-14T15:33:33Z" level=debug msg="[0/18] [open-vm-tools]: Adding "
time="2017-11-14T15:33:33Z" level=debug msg="[0/18] [acpid]: Adding "
time="2017-11-14T15:33:33Z" level=info msg="Project [os]: Starting project "
--
time="2017-11-14T15:33:33Z" level=debug msg="Launching action for docker"
time="2017-11-14T15:33:33Z" level=debug msg="Launching action for acpid"
time="2017-11-14T15:33:33Z" level=debug msg="Launching action for open-vm-tools"
time="2017-11-14T15:33:33Z" level=debug msg="Created container 6b6a5586680e7e6de1226fa12673e707b948f27b6dc00926190f17f449392e64: /system-volumes"
time="2017-11-14T15:33:33Z" level=debug msg="[0/19] [system-volumes]: Created container name=system-volumes"
--
time="2017-11-14T15:33:35Z" level=debug msg="Launching action for docker"
time="2017-11-14T15:33:35Z" level=debug msg="Launching action for acpid"
time="2017-11-14T15:33:35Z" level=debug msg="Launching action for open-vm-tools"
time="2017-11-14T15:33:35Z" level=debug msg="Creating container ntp &docker.ConfigWrapper{Config:(*container.Config)(0xc42027b0e0), HostConfig:(*container.HostConfig)(0xc420220000), NetworkingConfig:(*network.NetworkingConfig)(nil)}"
time="2017-11-14T15:33:35Z" level=info msg="[13/19] [open-vm-tools]: Starting "
time="2017-11-14T15:33:35Z" level=debug msg="Launching action for logrotate"
time="2017-11-14T15:33:35Z" level=debug msg="Launching action for syslog"
--
time="2017-11-14T15:33:36Z" level=debug msg="Starting container" c.name=preload-user-images container.ID=b5216d8d5142013797ad4064393b25072cd1bafc215c5a40f0bd8651e8180342
time="2017-11-14T15:33:37Z" level=debug msg="[17/19] [preload-user-images]: Started container name=preload-user-images"
time="2017-11-14T15:34:23Z" level=debug msg="Creating container open-vm-tools &docker.ConfigWrapper{Config:(*container.Config)(0xc42027b200), HostConfig:(*container.HostConfig)(0xc4202c6000), NetworkingConfig:(*network.NetworkingConfig)(nil)}"
time="2017-11-14T15:34:23Z" level=debug msg="Failed to create container open-vm-tools: Error: No such image: rancher/os-openvmtools:v1.1.0"
time="2017-11-14T15:34:23Z" level=error msg="Failed Starting open-vm-tools : Error: No such image: rancher/os-openvmtools:v1.1.0"
time="2017-11-14T15:34:23Z" level=error msg="Failed to start: open-vm-tools : Error: No such image: rancher/os-openvmtools:v1.1.0"
time="2017-11-14T15:34:41Z" level=info msg="[18/19] [preload-user-images]: Started "
time="2017-11-14T15:34:41Z" level=info msg="Project [os]: Project started "
time="2017-11-14T15:34:41Z" level=error msg="Failed [2/4] start project: Error: No such image: rancher/os-openvmtools:v1.1.0"
time="2017-11-14T15:34:41Z" level=fatal msg="Error: No such image: rancher/os-openvmtools:v1.1.0"
```
full file attached: [ros-sysinit.log](https://github.com/rancher/os/files/1471468/ros-sysinit.log)


I can easily spin up more of these and provide more log files if there are other files that would be helpful.

**Comment by lucymhdavies** [comment] 2017-11-14 17:14
Would probably help if I provided those logs from the same VM, rather than from two separate VMs.

[cloud-init-execute.log](https://github.com/rancher/os/files/1471794/cloud-init-execute.log)
[cloud-init-save.log](https://github.com/rancher/os/files/1471795/cloud-init-save.log)
[dockerlaunch.log](https://github.com/rancher/os/files/1471796/dockerlaunch.log)
[init.log](https://github.com/rancher/os/files/1471797/init.log)
[netconf.log](https://github.com/rancher/os/files/1471798/netconf.log)
[respawn.log](https://github.com/rancher/os/files/1471799/respawn.log)
[ros-sysinit.log](https://github.com/rancher/os/files/1471800/ros-sysinit.log)

**Comment by igormrbean** [comment] 2018-03-19 14:12
I'm running into the exact same issue with 1.2.  I have exported the open-vm-tools from dockerhub, and placed the .tar.gz under /var/lib/rancher/preload/system-docker/  When the VM boots, it detects it, and try to load the open-vm-tools image in system-docker (which appararently it does, according to logs, and the .done), but when open-vm-tools kicks in, it pulls the same image from dockerhub.  If I prevent the VM from downloading from internet (bad dns, or default gw for instance), I can see from the logs that the system-docker tries to load it's container (and supposedly succeeds), but a "sudo system-docker images" indicates that the image isn't loaded/available.

**Comment by niusmallnan** [comment] 2018-04-09 02:06
Duplicate of #2297 
Close this one.

**Closed by niusmallnan** 2018-04-09 02:06 UTC
Labels: kind/question
